#include <stdio.h>
#include <stdlib.h>
typedef int R; typedef unsigned int U;
static int LOG; __attribute__((constructor)) static void _i(){LOG=getenv("CARRION_FMODLOG")!=0;}
static void lg(const char*n){ if(LOG){ fprintf(stderr,"[FMOD] %s\n",n); fflush(stderr);} }
R FMOD5_Channel_AddDSP(){ lg("FMOD5_Channel_AddDSP"); return 0; }
R FMOD5_Channel_AddFadePoint(){ lg("FMOD5_Channel_AddFadePoint"); return 0; }
R FMOD5_Channel_Get3DAttributes(){ lg("FMOD5_Channel_Get3DAttributes"); return 0; }
R FMOD5_Channel_Get3DConeOrientation(){ lg("FMOD5_Channel_Get3DConeOrientation"); return 0; }
R FMOD5_Channel_Get3DConeSettings(){ lg("FMOD5_Channel_Get3DConeSettings"); return 0; }
R FMOD5_Channel_Get3DCustomRolloff(){ lg("FMOD5_Channel_Get3DCustomRolloff"); return 0; }
R FMOD5_Channel_Get3DDistanceFilter(){ lg("FMOD5_Channel_Get3DDistanceFilter"); return 0; }
R FMOD5_Channel_Get3DDopplerLevel(){ lg("FMOD5_Channel_Get3DDopplerLevel"); return 0; }
R FMOD5_Channel_Get3DLevel(){ lg("FMOD5_Channel_Get3DLevel"); return 0; }
R FMOD5_Channel_Get3DMinMaxDistance(){ lg("FMOD5_Channel_Get3DMinMaxDistance"); return 0; }
R FMOD5_Channel_Get3DOcclusion(){ lg("FMOD5_Channel_Get3DOcclusion"); return 0; }
R FMOD5_Channel_Get3DSpread(){ lg("FMOD5_Channel_Get3DSpread"); return 0; }
R FMOD5_Channel_GetAudibility(){ lg("FMOD5_Channel_GetAudibility"); return 0; }
R FMOD5_Channel_GetChannelGroup(){ lg("FMOD5_Channel_GetChannelGroup"); return 0; }
R FMOD5_Channel_GetCurrentSound(){ lg("FMOD5_Channel_GetCurrentSound"); return 0; }
R FMOD5_Channel_GetDelay(){ lg("FMOD5_Channel_GetDelay"); return 0; }
R FMOD5_Channel_GetDSP(){ lg("FMOD5_Channel_GetDSP"); return 0; }
R FMOD5_Channel_GetDSPClock(){ lg("FMOD5_Channel_GetDSPClock"); return 0; }
R FMOD5_Channel_GetDSPIndex(){ lg("FMOD5_Channel_GetDSPIndex"); return 0; }
R FMOD5_Channel_GetFadePoints(){ lg("FMOD5_Channel_GetFadePoints"); return 0; }
R FMOD5_Channel_GetFrequency(){ lg("FMOD5_Channel_GetFrequency"); return 0; }
R FMOD5_Channel_GetIndex(){ lg("FMOD5_Channel_GetIndex"); return 0; }
R FMOD5_Channel_GetLoopCount(){ lg("FMOD5_Channel_GetLoopCount"); return 0; }
R FMOD5_Channel_GetLoopPoints(){ lg("FMOD5_Channel_GetLoopPoints"); return 0; }
R FMOD5_Channel_GetLowPassGain(){ lg("FMOD5_Channel_GetLowPassGain"); return 0; }
R FMOD5_Channel_GetMixMatrix(){ lg("FMOD5_Channel_GetMixMatrix"); return 0; }
R FMOD5_Channel_GetMode(){ lg("FMOD5_Channel_GetMode"); return 0; }
R FMOD5_Channel_GetMute(){ lg("FMOD5_Channel_GetMute"); return 0; }
R FMOD5_Channel_GetNumDSPs(){ lg("FMOD5_Channel_GetNumDSPs"); return 0; }
R FMOD5_Channel_GetPaused(){ lg("FMOD5_Channel_GetPaused"); return 0; }
R FMOD5_Channel_GetPitch(){ lg("FMOD5_Channel_GetPitch"); return 0; }
R FMOD5_Channel_GetPosition(){ lg("FMOD5_Channel_GetPosition"); return 0; }
R FMOD5_Channel_GetPriority(){ lg("FMOD5_Channel_GetPriority"); return 0; }
R FMOD5_Channel_GetReverbProperties(){ lg("FMOD5_Channel_GetReverbProperties"); return 0; }
R FMOD5_Channel_GetSystemObject(){ lg("FMOD5_Channel_GetSystemObject"); return 0; }
R FMOD5_Channel_GetUserData(){ lg("FMOD5_Channel_GetUserData"); return 0; }
R FMOD5_Channel_GetVolume(){ lg("FMOD5_Channel_GetVolume"); return 0; }
R FMOD5_Channel_GetVolumeRamp(){ lg("FMOD5_Channel_GetVolumeRamp"); return 0; }
R FMOD5_ChannelGroup_AddDSP(){ lg("FMOD5_ChannelGroup_AddDSP"); return 0; }
R FMOD5_ChannelGroup_AddFadePoint(){ lg("FMOD5_ChannelGroup_AddFadePoint"); return 0; }
R FMOD5_ChannelGroup_AddGroup(){ lg("FMOD5_ChannelGroup_AddGroup"); return 0; }
R FMOD5_ChannelGroup_Get3DAttributes(){ lg("FMOD5_ChannelGroup_Get3DAttributes"); return 0; }
R FMOD5_ChannelGroup_Get3DConeOrientation(){ lg("FMOD5_ChannelGroup_Get3DConeOrientation"); return 0; }
R FMOD5_ChannelGroup_Get3DConeSettings(){ lg("FMOD5_ChannelGroup_Get3DConeSettings"); return 0; }
R FMOD5_ChannelGroup_Get3DCustomRolloff(){ lg("FMOD5_ChannelGroup_Get3DCustomRolloff"); return 0; }
R FMOD5_ChannelGroup_Get3DDistanceFilter(){ lg("FMOD5_ChannelGroup_Get3DDistanceFilter"); return 0; }
R FMOD5_ChannelGroup_Get3DDopplerLevel(){ lg("FMOD5_ChannelGroup_Get3DDopplerLevel"); return 0; }
R FMOD5_ChannelGroup_Get3DLevel(){ lg("FMOD5_ChannelGroup_Get3DLevel"); return 0; }
R FMOD5_ChannelGroup_Get3DMinMaxDistance(){ lg("FMOD5_ChannelGroup_Get3DMinMaxDistance"); return 0; }
R FMOD5_ChannelGroup_Get3DOcclusion(){ lg("FMOD5_ChannelGroup_Get3DOcclusion"); return 0; }
R FMOD5_ChannelGroup_Get3DSpread(){ lg("FMOD5_ChannelGroup_Get3DSpread"); return 0; }
R FMOD5_ChannelGroup_GetAudibility(){ lg("FMOD5_ChannelGroup_GetAudibility"); return 0; }
R FMOD5_ChannelGroup_GetChannel(){ lg("FMOD5_ChannelGroup_GetChannel"); return 0; }
R FMOD5_ChannelGroup_GetDelay(){ lg("FMOD5_ChannelGroup_GetDelay"); return 0; }
R FMOD5_ChannelGroup_GetDSP(){ lg("FMOD5_ChannelGroup_GetDSP"); return 0; }
R FMOD5_ChannelGroup_GetDSPClock(){ lg("FMOD5_ChannelGroup_GetDSPClock"); return 0; }
R FMOD5_ChannelGroup_GetDSPIndex(){ lg("FMOD5_ChannelGroup_GetDSPIndex"); return 0; }
R FMOD5_ChannelGroup_GetFadePoints(){ lg("FMOD5_ChannelGroup_GetFadePoints"); return 0; }
R FMOD5_ChannelGroup_GetGroup(){ lg("FMOD5_ChannelGroup_GetGroup"); return 0; }
R FMOD5_ChannelGroup_GetLowPassGain(){ lg("FMOD5_ChannelGroup_GetLowPassGain"); return 0; }
R FMOD5_ChannelGroup_GetMixMatrix(){ lg("FMOD5_ChannelGroup_GetMixMatrix"); return 0; }
R FMOD5_ChannelGroup_GetMode(){ lg("FMOD5_ChannelGroup_GetMode"); return 0; }
R FMOD5_ChannelGroup_GetMute(){ lg("FMOD5_ChannelGroup_GetMute"); return 0; }
R FMOD5_ChannelGroup_GetName(){ lg("FMOD5_ChannelGroup_GetName"); return 0; }
R FMOD5_ChannelGroup_GetNumChannels(){ lg("FMOD5_ChannelGroup_GetNumChannels"); return 0; }
R FMOD5_ChannelGroup_GetNumDSPs(){ lg("FMOD5_ChannelGroup_GetNumDSPs"); return 0; }
R FMOD5_ChannelGroup_GetNumGroups(){ lg("FMOD5_ChannelGroup_GetNumGroups"); return 0; }
R FMOD5_ChannelGroup_GetParentGroup(){ lg("FMOD5_ChannelGroup_GetParentGroup"); return 0; }
R FMOD5_ChannelGroup_GetPaused(){ lg("FMOD5_ChannelGroup_GetPaused"); return 0; }
R FMOD5_ChannelGroup_GetPitch(){ lg("FMOD5_ChannelGroup_GetPitch"); return 0; }
R FMOD5_ChannelGroup_GetReverbProperties(){ lg("FMOD5_ChannelGroup_GetReverbProperties"); return 0; }
R FMOD5_ChannelGroup_GetSystemObject(){ lg("FMOD5_ChannelGroup_GetSystemObject"); return 0; }
R FMOD5_ChannelGroup_GetUserData(){ lg("FMOD5_ChannelGroup_GetUserData"); return 0; }
R FMOD5_ChannelGroup_GetVolume(){ lg("FMOD5_ChannelGroup_GetVolume"); return 0; }
R FMOD5_ChannelGroup_GetVolumeRamp(){ lg("FMOD5_ChannelGroup_GetVolumeRamp"); return 0; }
R FMOD5_ChannelGroup_IsPlaying(){ lg("FMOD5_ChannelGroup_IsPlaying"); return 0; }
R FMOD5_ChannelGroup_Release(){ lg("FMOD5_ChannelGroup_Release"); return 0; }
R FMOD5_ChannelGroup_RemoveDSP(){ lg("FMOD5_ChannelGroup_RemoveDSP"); return 0; }
R FMOD5_ChannelGroup_RemoveFadePoints(){ lg("FMOD5_ChannelGroup_RemoveFadePoints"); return 0; }
R FMOD5_ChannelGroup_Set3DAttributes(){ lg("FMOD5_ChannelGroup_Set3DAttributes"); return 0; }
R FMOD5_ChannelGroup_Set3DConeOrientation(){ lg("FMOD5_ChannelGroup_Set3DConeOrientation"); return 0; }
R FMOD5_ChannelGroup_Set3DConeSettings(){ lg("FMOD5_ChannelGroup_Set3DConeSettings"); return 0; }
R FMOD5_ChannelGroup_Set3DCustomRolloff(){ lg("FMOD5_ChannelGroup_Set3DCustomRolloff"); return 0; }
R FMOD5_ChannelGroup_Set3DDistanceFilter(){ lg("FMOD5_ChannelGroup_Set3DDistanceFilter"); return 0; }
R FMOD5_ChannelGroup_Set3DDopplerLevel(){ lg("FMOD5_ChannelGroup_Set3DDopplerLevel"); return 0; }
R FMOD5_ChannelGroup_Set3DLevel(){ lg("FMOD5_ChannelGroup_Set3DLevel"); return 0; }
R FMOD5_ChannelGroup_Set3DMinMaxDistance(){ lg("FMOD5_ChannelGroup_Set3DMinMaxDistance"); return 0; }
R FMOD5_ChannelGroup_Set3DOcclusion(){ lg("FMOD5_ChannelGroup_Set3DOcclusion"); return 0; }
R FMOD5_ChannelGroup_Set3DSpread(){ lg("FMOD5_ChannelGroup_Set3DSpread"); return 0; }
R FMOD5_ChannelGroup_SetCallback(){ lg("FMOD5_ChannelGroup_SetCallback"); return 0; }
R FMOD5_ChannelGroup_SetDelay(){ lg("FMOD5_ChannelGroup_SetDelay"); return 0; }
R FMOD5_ChannelGroup_SetDSPIndex(){ lg("FMOD5_ChannelGroup_SetDSPIndex"); return 0; }
R FMOD5_ChannelGroup_SetFadePointRamp(){ lg("FMOD5_ChannelGroup_SetFadePointRamp"); return 0; }
R FMOD5_ChannelGroup_SetLowPassGain(){ lg("FMOD5_ChannelGroup_SetLowPassGain"); return 0; }
R FMOD5_ChannelGroup_SetMixLevelsInput(){ lg("FMOD5_ChannelGroup_SetMixLevelsInput"); return 0; }
R FMOD5_ChannelGroup_SetMixLevelsOutput(){ lg("FMOD5_ChannelGroup_SetMixLevelsOutput"); return 0; }
R FMOD5_ChannelGroup_SetMixMatrix(){ lg("FMOD5_ChannelGroup_SetMixMatrix"); return 0; }
R FMOD5_ChannelGroup_SetMode(){ lg("FMOD5_ChannelGroup_SetMode"); return 0; }
R FMOD5_ChannelGroup_SetMute(){ lg("FMOD5_ChannelGroup_SetMute"); return 0; }
R FMOD5_ChannelGroup_SetPan(){ lg("FMOD5_ChannelGroup_SetPan"); return 0; }
R FMOD5_ChannelGroup_SetPaused(){ lg("FMOD5_ChannelGroup_SetPaused"); return 0; }
R FMOD5_ChannelGroup_SetPitch(){ lg("FMOD5_ChannelGroup_SetPitch"); return 0; }
R FMOD5_ChannelGroup_SetReverbProperties(){ lg("FMOD5_ChannelGroup_SetReverbProperties"); return 0; }
R FMOD5_ChannelGroup_SetUserData(){ lg("FMOD5_ChannelGroup_SetUserData"); return 0; }
R FMOD5_ChannelGroup_SetVolume(){ lg("FMOD5_ChannelGroup_SetVolume"); return 0; }
R FMOD5_ChannelGroup_SetVolumeRamp(){ lg("FMOD5_ChannelGroup_SetVolumeRamp"); return 0; }
R FMOD5_ChannelGroup_Stop(){ lg("FMOD5_ChannelGroup_Stop"); return 0; }
R FMOD5_Channel_IsPlaying(){ lg("FMOD5_Channel_IsPlaying"); return 0; }
R FMOD5_Channel_IsVirtual(){ lg("FMOD5_Channel_IsVirtual"); return 0; }
R FMOD5_Channel_RemoveDSP(){ lg("FMOD5_Channel_RemoveDSP"); return 0; }
R FMOD5_Channel_RemoveFadePoints(){ lg("FMOD5_Channel_RemoveFadePoints"); return 0; }
R FMOD5_Channel_Set3DAttributes(){ lg("FMOD5_Channel_Set3DAttributes"); return 0; }
R FMOD5_Channel_Set3DConeOrientation(){ lg("FMOD5_Channel_Set3DConeOrientation"); return 0; }
R FMOD5_Channel_Set3DConeSettings(){ lg("FMOD5_Channel_Set3DConeSettings"); return 0; }
R FMOD5_Channel_Set3DCustomRolloff(){ lg("FMOD5_Channel_Set3DCustomRolloff"); return 0; }
R FMOD5_Channel_Set3DDistanceFilter(){ lg("FMOD5_Channel_Set3DDistanceFilter"); return 0; }
R FMOD5_Channel_Set3DDopplerLevel(){ lg("FMOD5_Channel_Set3DDopplerLevel"); return 0; }
R FMOD5_Channel_Set3DLevel(){ lg("FMOD5_Channel_Set3DLevel"); return 0; }
R FMOD5_Channel_Set3DMinMaxDistance(){ lg("FMOD5_Channel_Set3DMinMaxDistance"); return 0; }
R FMOD5_Channel_Set3DOcclusion(){ lg("FMOD5_Channel_Set3DOcclusion"); return 0; }
R FMOD5_Channel_Set3DSpread(){ lg("FMOD5_Channel_Set3DSpread"); return 0; }
R FMOD5_Channel_SetCallback(){ lg("FMOD5_Channel_SetCallback"); return 0; }
R FMOD5_Channel_SetChannelGroup(){ lg("FMOD5_Channel_SetChannelGroup"); return 0; }
R FMOD5_Channel_SetDelay(){ lg("FMOD5_Channel_SetDelay"); return 0; }
R FMOD5_Channel_SetDSPIndex(){ lg("FMOD5_Channel_SetDSPIndex"); return 0; }
R FMOD5_Channel_SetFadePointRamp(){ lg("FMOD5_Channel_SetFadePointRamp"); return 0; }
R FMOD5_Channel_SetFrequency(){ lg("FMOD5_Channel_SetFrequency"); return 0; }
R FMOD5_Channel_SetLoopCount(){ lg("FMOD5_Channel_SetLoopCount"); return 0; }
R FMOD5_Channel_SetLoopPoints(){ lg("FMOD5_Channel_SetLoopPoints"); return 0; }
R FMOD5_Channel_SetLowPassGain(){ lg("FMOD5_Channel_SetLowPassGain"); return 0; }
R FMOD5_Channel_SetMixLevelsInput(){ lg("FMOD5_Channel_SetMixLevelsInput"); return 0; }
R FMOD5_Channel_SetMixLevelsOutput(){ lg("FMOD5_Channel_SetMixLevelsOutput"); return 0; }
R FMOD5_Channel_SetMixMatrix(){ lg("FMOD5_Channel_SetMixMatrix"); return 0; }
R FMOD5_Channel_SetMode(){ lg("FMOD5_Channel_SetMode"); return 0; }
R FMOD5_Channel_SetMute(){ lg("FMOD5_Channel_SetMute"); return 0; }
R FMOD5_Channel_SetPan(){ lg("FMOD5_Channel_SetPan"); return 0; }
R FMOD5_Channel_SetPaused(){ lg("FMOD5_Channel_SetPaused"); return 0; }
R FMOD5_Channel_SetPitch(){ lg("FMOD5_Channel_SetPitch"); return 0; }
R FMOD5_Channel_SetPosition(){ lg("FMOD5_Channel_SetPosition"); return 0; }
R FMOD5_Channel_SetPriority(){ lg("FMOD5_Channel_SetPriority"); return 0; }
R FMOD5_Channel_SetReverbProperties(){ lg("FMOD5_Channel_SetReverbProperties"); return 0; }
R FMOD5_Channel_SetUserData(){ lg("FMOD5_Channel_SetUserData"); return 0; }
R FMOD5_Channel_SetVolume(){ lg("FMOD5_Channel_SetVolume"); return 0; }
R FMOD5_Channel_SetVolumeRamp(){ lg("FMOD5_Channel_SetVolumeRamp"); return 0; }
R FMOD5_Channel_Stop(){ lg("FMOD5_Channel_Stop"); return 0; }
R FMOD5_Debug_Initialize(){ lg("FMOD5_Debug_Initialize"); return 0; }
R FMOD5_DSP_AddInput(){ lg("FMOD5_DSP_AddInput"); return 0; }
R FMOD5_DSPConnection_GetInput(){ lg("FMOD5_DSPConnection_GetInput"); return 0; }
R FMOD5_DSPConnection_GetMix(){ lg("FMOD5_DSPConnection_GetMix"); return 0; }
R FMOD5_DSPConnection_GetMixMatrix(){ lg("FMOD5_DSPConnection_GetMixMatrix"); return 0; }
R FMOD5_DSPConnection_GetOutput(){ lg("FMOD5_DSPConnection_GetOutput"); return 0; }
R FMOD5_DSPConnection_GetType(){ lg("FMOD5_DSPConnection_GetType"); return 0; }
R FMOD5_DSPConnection_GetUserData(){ lg("FMOD5_DSPConnection_GetUserData"); return 0; }
R FMOD5_DSPConnection_SetMix(){ lg("FMOD5_DSPConnection_SetMix"); return 0; }
R FMOD5_DSPConnection_SetMixMatrix(){ lg("FMOD5_DSPConnection_SetMixMatrix"); return 0; }
R FMOD5_DSPConnection_SetUserData(){ lg("FMOD5_DSPConnection_SetUserData"); return 0; }
R FMOD5_DSP_DisconnectAll(){ lg("FMOD5_DSP_DisconnectAll"); return 0; }
R FMOD5_DSP_DisconnectFrom(){ lg("FMOD5_DSP_DisconnectFrom"); return 0; }
R FMOD5_DSP_GetActive(){ lg("FMOD5_DSP_GetActive"); return 0; }
R FMOD5_DSP_GetBypass(){ lg("FMOD5_DSP_GetBypass"); return 0; }
R FMOD5_DSP_GetChannelFormat(){ lg("FMOD5_DSP_GetChannelFormat"); return 0; }
R FMOD5_DSP_GetCPUUsage(){ lg("FMOD5_DSP_GetCPUUsage"); return 0; }
R FMOD5_DSP_GetDataParameterIndex(){ lg("FMOD5_DSP_GetDataParameterIndex"); return 0; }
R FMOD5_DSP_GetIdle(){ lg("FMOD5_DSP_GetIdle"); return 0; }
R FMOD5_DSP_GetInfo(){ lg("FMOD5_DSP_GetInfo"); return 0; }
R FMOD5_DSP_GetInput(){ lg("FMOD5_DSP_GetInput"); return 0; }
R FMOD5_DSP_GetMeteringEnabled(){ lg("FMOD5_DSP_GetMeteringEnabled"); return 0; }
R FMOD5_DSP_GetMeteringInfo(){ lg("FMOD5_DSP_GetMeteringInfo"); return 0; }
R FMOD5_DSP_GetNumInputs(){ lg("FMOD5_DSP_GetNumInputs"); return 0; }
R FMOD5_DSP_GetNumOutputs(){ lg("FMOD5_DSP_GetNumOutputs"); return 0; }
R FMOD5_DSP_GetNumParameters(){ lg("FMOD5_DSP_GetNumParameters"); return 0; }
R FMOD5_DSP_GetOutput(){ lg("FMOD5_DSP_GetOutput"); return 0; }
R FMOD5_DSP_GetOutputChannelFormat(){ lg("FMOD5_DSP_GetOutputChannelFormat"); return 0; }
R FMOD5_DSP_GetParameterBool(){ lg("FMOD5_DSP_GetParameterBool"); return 0; }
R FMOD5_DSP_GetParameterData(){ lg("FMOD5_DSP_GetParameterData"); return 0; }
R FMOD5_DSP_GetParameterFloat(){ lg("FMOD5_DSP_GetParameterFloat"); return 0; }
R FMOD5_DSP_GetParameterInfo(){ lg("FMOD5_DSP_GetParameterInfo"); return 0; }
R FMOD5_DSP_GetParameterInt(){ lg("FMOD5_DSP_GetParameterInt"); return 0; }
R FMOD5_DSP_GetSystemObject(){ lg("FMOD5_DSP_GetSystemObject"); return 0; }
R FMOD5_DSP_GetType(){ lg("FMOD5_DSP_GetType"); return 0; }
R FMOD5_DSP_GetUserData(){ lg("FMOD5_DSP_GetUserData"); return 0; }
R FMOD5_DSP_GetWetDryMix(){ lg("FMOD5_DSP_GetWetDryMix"); return 0; }
R FMOD5_DSP_Release(){ lg("FMOD5_DSP_Release"); return 0; }
R FMOD5_DSP_Reset(){ lg("FMOD5_DSP_Reset"); return 0; }
R FMOD5_DSP_SetActive(){ lg("FMOD5_DSP_SetActive"); return 0; }
R FMOD5_DSP_SetBypass(){ lg("FMOD5_DSP_SetBypass"); return 0; }
R FMOD5_DSP_SetCallback(){ lg("FMOD5_DSP_SetCallback"); return 0; }
R FMOD5_DSP_SetChannelFormat(){ lg("FMOD5_DSP_SetChannelFormat"); return 0; }
R FMOD5_DSP_SetMeteringEnabled(){ lg("FMOD5_DSP_SetMeteringEnabled"); return 0; }
R FMOD5_DSP_SetParameterBool(){ lg("FMOD5_DSP_SetParameterBool"); return 0; }
R FMOD5_DSP_SetParameterData(){ lg("FMOD5_DSP_SetParameterData"); return 0; }
R FMOD5_DSP_SetParameterFloat(){ lg("FMOD5_DSP_SetParameterFloat"); return 0; }
R FMOD5_DSP_SetParameterInt(){ lg("FMOD5_DSP_SetParameterInt"); return 0; }
R FMOD5_DSP_SetUserData(){ lg("FMOD5_DSP_SetUserData"); return 0; }
R FMOD5_DSP_SetWetDryMix(){ lg("FMOD5_DSP_SetWetDryMix"); return 0; }
R FMOD5_DSP_ShowConfigDialog(){ lg("FMOD5_DSP_ShowConfigDialog"); return 0; }
R FMOD5_Geometry_AddPolygon(){ lg("FMOD5_Geometry_AddPolygon"); return 0; }
R FMOD5_Geometry_GetActive(){ lg("FMOD5_Geometry_GetActive"); return 0; }
R FMOD5_Geometry_GetMaxPolygons(){ lg("FMOD5_Geometry_GetMaxPolygons"); return 0; }
R FMOD5_Geometry_GetNumPolygons(){ lg("FMOD5_Geometry_GetNumPolygons"); return 0; }
R FMOD5_Geometry_GetPolygonAttributes(){ lg("FMOD5_Geometry_GetPolygonAttributes"); return 0; }
R FMOD5_Geometry_GetPolygonNumVertices(){ lg("FMOD5_Geometry_GetPolygonNumVertices"); return 0; }
R FMOD5_Geometry_GetPolygonVertex(){ lg("FMOD5_Geometry_GetPolygonVertex"); return 0; }
R FMOD5_Geometry_GetPosition(){ lg("FMOD5_Geometry_GetPosition"); return 0; }
R FMOD5_Geometry_GetRotation(){ lg("FMOD5_Geometry_GetRotation"); return 0; }
R FMOD5_Geometry_GetScale(){ lg("FMOD5_Geometry_GetScale"); return 0; }
R FMOD5_Geometry_GetUserData(){ lg("FMOD5_Geometry_GetUserData"); return 0; }
R FMOD5_Geometry_Release(){ lg("FMOD5_Geometry_Release"); return 0; }
R FMOD5_Geometry_Save(){ lg("FMOD5_Geometry_Save"); return 0; }
R FMOD5_Geometry_SetActive(){ lg("FMOD5_Geometry_SetActive"); return 0; }
R FMOD5_Geometry_SetPolygonAttributes(){ lg("FMOD5_Geometry_SetPolygonAttributes"); return 0; }
R FMOD5_Geometry_SetPolygonVertex(){ lg("FMOD5_Geometry_SetPolygonVertex"); return 0; }
R FMOD5_Geometry_SetPosition(){ lg("FMOD5_Geometry_SetPosition"); return 0; }
R FMOD5_Geometry_SetRotation(){ lg("FMOD5_Geometry_SetRotation"); return 0; }
R FMOD5_Geometry_SetScale(){ lg("FMOD5_Geometry_SetScale"); return 0; }
R FMOD5_Geometry_SetUserData(){ lg("FMOD5_Geometry_SetUserData"); return 0; }
R FMOD5_Memory_GetStats(){ lg("FMOD5_Memory_GetStats"); return 0; }
R FMOD5_Memory_Initialize(){ lg("FMOD5_Memory_Initialize"); return 0; }
R FMOD5_Reverb3D_Get3DAttributes(){ lg("FMOD5_Reverb3D_Get3DAttributes"); return 0; }
R FMOD5_Reverb3D_GetActive(){ lg("FMOD5_Reverb3D_GetActive"); return 0; }
R FMOD5_Reverb3D_GetProperties(){ lg("FMOD5_Reverb3D_GetProperties"); return 0; }
R FMOD5_Reverb3D_GetUserData(){ lg("FMOD5_Reverb3D_GetUserData"); return 0; }
R FMOD5_Reverb3D_Release(){ lg("FMOD5_Reverb3D_Release"); return 0; }
R FMOD5_Reverb3D_Set3DAttributes(){ lg("FMOD5_Reverb3D_Set3DAttributes"); return 0; }
R FMOD5_Reverb3D_SetActive(){ lg("FMOD5_Reverb3D_SetActive"); return 0; }
R FMOD5_Reverb3D_SetProperties(){ lg("FMOD5_Reverb3D_SetProperties"); return 0; }
R FMOD5_Reverb3D_SetUserData(){ lg("FMOD5_Reverb3D_SetUserData"); return 0; }
R FMOD5_Sound_AddSyncPoint(){ lg("FMOD5_Sound_AddSyncPoint"); return 0; }
R FMOD5_Sound_DeleteSyncPoint(){ lg("FMOD5_Sound_DeleteSyncPoint"); return 0; }
R FMOD5_Sound_Get3DConeSettings(){ lg("FMOD5_Sound_Get3DConeSettings"); return 0; }
R FMOD5_Sound_Get3DCustomRolloff(){ lg("FMOD5_Sound_Get3DCustomRolloff"); return 0; }
R FMOD5_Sound_Get3DMinMaxDistance(){ lg("FMOD5_Sound_Get3DMinMaxDistance"); return 0; }
R FMOD5_Sound_GetDefaults(){ lg("FMOD5_Sound_GetDefaults"); return 0; }
R FMOD5_Sound_GetFormat(){ lg("FMOD5_Sound_GetFormat"); return 0; }
R FMOD5_Sound_GetLength(){ lg("FMOD5_Sound_GetLength"); return 0; }
R FMOD5_Sound_GetLoopCount(){ lg("FMOD5_Sound_GetLoopCount"); return 0; }
R FMOD5_Sound_GetLoopPoints(){ lg("FMOD5_Sound_GetLoopPoints"); return 0; }
R FMOD5_Sound_GetMode(){ lg("FMOD5_Sound_GetMode"); return 0; }
R FMOD5_Sound_GetMusicChannelVolume(){ lg("FMOD5_Sound_GetMusicChannelVolume"); return 0; }
R FMOD5_Sound_GetMusicNumChannels(){ lg("FMOD5_Sound_GetMusicNumChannels"); return 0; }
R FMOD5_Sound_GetMusicSpeed(){ lg("FMOD5_Sound_GetMusicSpeed"); return 0; }
R FMOD5_Sound_GetName(){ lg("FMOD5_Sound_GetName"); return 0; }
R FMOD5_Sound_GetNumSubSounds(){ lg("FMOD5_Sound_GetNumSubSounds"); return 0; }
R FMOD5_Sound_GetNumSyncPoints(){ lg("FMOD5_Sound_GetNumSyncPoints"); return 0; }
R FMOD5_Sound_GetNumTags(){ lg("FMOD5_Sound_GetNumTags"); return 0; }
R FMOD5_Sound_GetOpenState(){ lg("FMOD5_Sound_GetOpenState"); return 0; }
R FMOD5_Sound_GetSoundGroup(){ lg("FMOD5_Sound_GetSoundGroup"); return 0; }
R FMOD5_Sound_GetSubSound(){ lg("FMOD5_Sound_GetSubSound"); return 0; }
R FMOD5_Sound_GetSubSoundParent(){ lg("FMOD5_Sound_GetSubSoundParent"); return 0; }
R FMOD5_Sound_GetSyncPoint(){ lg("FMOD5_Sound_GetSyncPoint"); return 0; }
R FMOD5_Sound_GetSyncPointInfo(){ lg("FMOD5_Sound_GetSyncPointInfo"); return 0; }
R FMOD5_Sound_GetSystemObject(){ lg("FMOD5_Sound_GetSystemObject"); return 0; }
R FMOD5_Sound_GetTag(){ lg("FMOD5_Sound_GetTag"); return 0; }
R FMOD5_Sound_GetUserData(){ lg("FMOD5_Sound_GetUserData"); return 0; }
R FMOD5_SoundGroup_GetMaxAudible(){ lg("FMOD5_SoundGroup_GetMaxAudible"); return 0; }
R FMOD5_SoundGroup_GetMaxAudibleBehavior(){ lg("FMOD5_SoundGroup_GetMaxAudibleBehavior"); return 0; }
R FMOD5_SoundGroup_GetMuteFadeSpeed(){ lg("FMOD5_SoundGroup_GetMuteFadeSpeed"); return 0; }
R FMOD5_SoundGroup_GetName(){ lg("FMOD5_SoundGroup_GetName"); return 0; }
R FMOD5_SoundGroup_GetNumPlaying(){ lg("FMOD5_SoundGroup_GetNumPlaying"); return 0; }
R FMOD5_SoundGroup_GetNumSounds(){ lg("FMOD5_SoundGroup_GetNumSounds"); return 0; }
R FMOD5_SoundGroup_GetSound(){ lg("FMOD5_SoundGroup_GetSound"); return 0; }
R FMOD5_SoundGroup_GetSystemObject(){ lg("FMOD5_SoundGroup_GetSystemObject"); return 0; }
R FMOD5_SoundGroup_GetUserData(){ lg("FMOD5_SoundGroup_GetUserData"); return 0; }
R FMOD5_SoundGroup_GetVolume(){ lg("FMOD5_SoundGroup_GetVolume"); return 0; }
R FMOD5_SoundGroup_Release(){ lg("FMOD5_SoundGroup_Release"); return 0; }
R FMOD5_SoundGroup_SetMaxAudible(){ lg("FMOD5_SoundGroup_SetMaxAudible"); return 0; }
R FMOD5_SoundGroup_SetMaxAudibleBehavior(){ lg("FMOD5_SoundGroup_SetMaxAudibleBehavior"); return 0; }
R FMOD5_SoundGroup_SetMuteFadeSpeed(){ lg("FMOD5_SoundGroup_SetMuteFadeSpeed"); return 0; }
R FMOD5_SoundGroup_SetUserData(){ lg("FMOD5_SoundGroup_SetUserData"); return 0; }
R FMOD5_SoundGroup_SetVolume(){ lg("FMOD5_SoundGroup_SetVolume"); return 0; }
R FMOD5_SoundGroup_Stop(){ lg("FMOD5_SoundGroup_Stop"); return 0; }
R FMOD5_Sound_Lock(){ lg("FMOD5_Sound_Lock"); return 0; }
R FMOD5_Sound_ReadData(){ lg("FMOD5_Sound_ReadData"); return 0; }
R FMOD5_Sound_Release(){ lg("FMOD5_Sound_Release"); return 0; }
R FMOD5_Sound_SeekData(){ lg("FMOD5_Sound_SeekData"); return 0; }
R FMOD5_Sound_Set3DConeSettings(){ lg("FMOD5_Sound_Set3DConeSettings"); return 0; }
R FMOD5_Sound_Set3DCustomRolloff(){ lg("FMOD5_Sound_Set3DCustomRolloff"); return 0; }
R FMOD5_Sound_Set3DMinMaxDistance(){ lg("FMOD5_Sound_Set3DMinMaxDistance"); return 0; }
R FMOD5_Sound_SetDefaults(){ lg("FMOD5_Sound_SetDefaults"); return 0; }
R FMOD5_Sound_SetLoopCount(){ lg("FMOD5_Sound_SetLoopCount"); return 0; }
R FMOD5_Sound_SetLoopPoints(){ lg("FMOD5_Sound_SetLoopPoints"); return 0; }
R FMOD5_Sound_SetMode(){ lg("FMOD5_Sound_SetMode"); return 0; }
R FMOD5_Sound_SetMusicChannelVolume(){ lg("FMOD5_Sound_SetMusicChannelVolume"); return 0; }
R FMOD5_Sound_SetMusicSpeed(){ lg("FMOD5_Sound_SetMusicSpeed"); return 0; }
R FMOD5_Sound_SetSoundGroup(){ lg("FMOD5_Sound_SetSoundGroup"); return 0; }
R FMOD5_Sound_SetUserData(){ lg("FMOD5_Sound_SetUserData"); return 0; }
R FMOD5_Sound_Unlock(){ lg("FMOD5_Sound_Unlock"); return 0; }
R FMOD5_System_AttachChannelGroupToPort(){ lg("FMOD5_System_AttachChannelGroupToPort"); return 0; }
R FMOD5_System_AttachFileSystem(){ lg("FMOD5_System_AttachFileSystem"); return 0; }
R FMOD5_System_Close(){ lg("FMOD5_System_Close"); return 0; }
R FMOD5_System_Create(){ lg("FMOD5_System_Create"); return 0; }
R FMOD5_System_CreateChannelGroup(){ lg("FMOD5_System_CreateChannelGroup"); return 0; }
R FMOD5_System_CreateDSP(){ lg("FMOD5_System_CreateDSP"); return 0; }
R FMOD5_System_CreateDSPByPlugin(){ lg("FMOD5_System_CreateDSPByPlugin"); return 0; }
R FMOD5_System_CreateDSPByType(){ lg("FMOD5_System_CreateDSPByType"); return 0; }
R FMOD5_System_CreateGeometry(){ lg("FMOD5_System_CreateGeometry"); return 0; }
R FMOD5_System_CreateReverb3D(){ lg("FMOD5_System_CreateReverb3D"); return 0; }
R FMOD5_System_CreateSound(){ lg("FMOD5_System_CreateSound"); return 0; }
R FMOD5_System_CreateSoundGroup(){ lg("FMOD5_System_CreateSoundGroup"); return 0; }
R FMOD5_System_CreateStream(){ lg("FMOD5_System_CreateStream"); return 0; }
R FMOD5_System_DetachChannelGroupFromPort(){ lg("FMOD5_System_DetachChannelGroupFromPort"); return 0; }
R FMOD5_System_Get3DListenerAttributes(){ lg("FMOD5_System_Get3DListenerAttributes"); return 0; }
R FMOD5_System_Get3DNumListeners(){ lg("FMOD5_System_Get3DNumListeners"); return 0; }
R FMOD5_System_Get3DSettings(){ lg("FMOD5_System_Get3DSettings"); return 0; }
R FMOD5_System_GetAdvancedSettings(){ lg("FMOD5_System_GetAdvancedSettings"); return 0; }
R FMOD5_System_GetChannel(){ lg("FMOD5_System_GetChannel"); return 0; }
R FMOD5_System_GetChannelsPlaying(){ lg("FMOD5_System_GetChannelsPlaying"); return 0; }
R FMOD5_System_GetCPUUsage(){ lg("FMOD5_System_GetCPUUsage"); return 0; }
R FMOD5_System_GetDefaultMixMatrix(){ lg("FMOD5_System_GetDefaultMixMatrix"); return 0; }
R FMOD5_System_GetDriver(){ lg("FMOD5_System_GetDriver"); return 0; }
R FMOD5_System_GetDriverInfo(){ lg("FMOD5_System_GetDriverInfo"); return 0; }
R FMOD5_System_GetDSPBufferSize(){ lg("FMOD5_System_GetDSPBufferSize"); return 0; }
R FMOD5_System_GetDSPInfoByPlugin(){ lg("FMOD5_System_GetDSPInfoByPlugin"); return 0; }
R FMOD5_System_GetDSPInfoByType(){ lg("FMOD5_System_GetDSPInfoByType"); return 0; }
R FMOD5_System_GetFileUsage(){ lg("FMOD5_System_GetFileUsage"); return 0; }
R FMOD5_System_GetGeometryOcclusion(){ lg("FMOD5_System_GetGeometryOcclusion"); return 0; }
R FMOD5_System_GetGeometrySettings(){ lg("FMOD5_System_GetGeometrySettings"); return 0; }
R FMOD5_System_GetMasterChannelGroup(){ lg("FMOD5_System_GetMasterChannelGroup"); return 0; }
R FMOD5_System_GetMasterSoundGroup(){ lg("FMOD5_System_GetMasterSoundGroup"); return 0; }
R FMOD5_System_GetNestedPlugin(){ lg("FMOD5_System_GetNestedPlugin"); return 0; }
R FMOD5_System_GetNetworkProxy(){ lg("FMOD5_System_GetNetworkProxy"); return 0; }
R FMOD5_System_GetNetworkTimeout(){ lg("FMOD5_System_GetNetworkTimeout"); return 0; }
R FMOD5_System_GetNumDrivers(){ lg("FMOD5_System_GetNumDrivers"); return 0; }
R FMOD5_System_GetNumNestedPlugins(){ lg("FMOD5_System_GetNumNestedPlugins"); return 0; }
R FMOD5_System_GetNumPlugins(){ lg("FMOD5_System_GetNumPlugins"); return 0; }
R FMOD5_System_GetOutput(){ lg("FMOD5_System_GetOutput"); return 0; }
R FMOD5_System_GetOutputByPlugin(){ lg("FMOD5_System_GetOutputByPlugin"); return 0; }
R FMOD5_System_GetOutputHandle(){ lg("FMOD5_System_GetOutputHandle"); return 0; }
R FMOD5_System_GetPluginHandle(){ lg("FMOD5_System_GetPluginHandle"); return 0; }
R FMOD5_System_GetPluginInfo(){ lg("FMOD5_System_GetPluginInfo"); return 0; }
R FMOD5_System_GetRecordDriverInfo(){ lg("FMOD5_System_GetRecordDriverInfo"); return 0; }
R FMOD5_System_GetRecordNumDrivers(){ lg("FMOD5_System_GetRecordNumDrivers"); return 0; }
R FMOD5_System_GetRecordPosition(){ lg("FMOD5_System_GetRecordPosition"); return 0; }
R FMOD5_System_GetReverbProperties(){ lg("FMOD5_System_GetReverbProperties"); return 0; }
R FMOD5_System_GetSoftwareChannels(){ lg("FMOD5_System_GetSoftwareChannels"); return 0; }
R FMOD5_System_GetSoftwareFormat(){ lg("FMOD5_System_GetSoftwareFormat"); return 0; }
R FMOD5_System_GetSpeakerModeChannels(){ lg("FMOD5_System_GetSpeakerModeChannels"); return 0; }
R FMOD5_System_GetSpeakerPosition(){ lg("FMOD5_System_GetSpeakerPosition"); return 0; }
R FMOD5_System_GetStreamBufferSize(){ lg("FMOD5_System_GetStreamBufferSize"); return 0; }
R FMOD5_System_GetUserData(){ lg("FMOD5_System_GetUserData"); return 0; }
R FMOD5_System_GetVersion(void* a, U* v){ lg("FMOD5_System_GetVersion"); if(v) *v=0x00020231; return 0; }
R FMOD5_System_Init(){ lg("FMOD5_System_Init"); return 0; }
R FMOD5_System_IsRecording(){ lg("FMOD5_System_IsRecording"); return 0; }
R FMOD5_System_LoadGeometry(){ lg("FMOD5_System_LoadGeometry"); return 0; }
R FMOD5_System_LoadPlugin(){ lg("FMOD5_System_LoadPlugin"); return 0; }
R FMOD5_System_LockDSP(){ lg("FMOD5_System_LockDSP"); return 0; }
R FMOD5_System_MixerResume(){ lg("FMOD5_System_MixerResume"); return 0; }
R FMOD5_System_MixerSuspend(){ lg("FMOD5_System_MixerSuspend"); return 0; }
R FMOD5_System_PlayDSP(){ lg("FMOD5_System_PlayDSP"); return 0; }
R FMOD5_System_PlaySound(){ lg("FMOD5_System_PlaySound"); return 0; }
R FMOD5_System_RecordStart(){ lg("FMOD5_System_RecordStart"); return 0; }
R FMOD5_System_RecordStop(){ lg("FMOD5_System_RecordStop"); return 0; }
R FMOD5_System_RegisterDSP(){ lg("FMOD5_System_RegisterDSP"); return 0; }
R FMOD5_System_Release(){ lg("FMOD5_System_Release"); return 0; }
R FMOD5_System_Set3DListenerAttributes(){ lg("FMOD5_System_Set3DListenerAttributes"); return 0; }
R FMOD5_System_Set3DNumListeners(){ lg("FMOD5_System_Set3DNumListeners"); return 0; }
R FMOD5_System_Set3DRolloffCallback(){ lg("FMOD5_System_Set3DRolloffCallback"); return 0; }
R FMOD5_System_Set3DSettings(){ lg("FMOD5_System_Set3DSettings"); return 0; }
R FMOD5_System_SetAdvancedSettings(){ lg("FMOD5_System_SetAdvancedSettings"); return 0; }
R FMOD5_System_SetCallback(){ lg("FMOD5_System_SetCallback"); return 0; }
R FMOD5_System_SetDriver(){ lg("FMOD5_System_SetDriver"); return 0; }
R FMOD5_System_SetDSPBufferSize(){ lg("FMOD5_System_SetDSPBufferSize"); return 0; }
R FMOD5_System_SetFileSystem(){ lg("FMOD5_System_SetFileSystem"); return 0; }
R FMOD5_System_SetGeometrySettings(){ lg("FMOD5_System_SetGeometrySettings"); return 0; }
R FMOD5_System_SetNetworkProxy(){ lg("FMOD5_System_SetNetworkProxy"); return 0; }
R FMOD5_System_SetNetworkTimeout(){ lg("FMOD5_System_SetNetworkTimeout"); return 0; }
R FMOD5_System_SetOutput(){ lg("FMOD5_System_SetOutput"); return 0; }
R FMOD5_System_SetOutputByPlugin(){ lg("FMOD5_System_SetOutputByPlugin"); return 0; }
R FMOD5_System_SetPluginPath(){ lg("FMOD5_System_SetPluginPath"); return 0; }
R FMOD5_System_SetReverbProperties(){ lg("FMOD5_System_SetReverbProperties"); return 0; }
R FMOD5_System_SetSoftwareChannels(){ lg("FMOD5_System_SetSoftwareChannels"); return 0; }
R FMOD5_System_SetSoftwareFormat(){ lg("FMOD5_System_SetSoftwareFormat"); return 0; }
R FMOD5_System_SetSpeakerPosition(){ lg("FMOD5_System_SetSpeakerPosition"); return 0; }
R FMOD5_System_SetStreamBufferSize(){ lg("FMOD5_System_SetStreamBufferSize"); return 0; }
R FMOD5_System_SetUserData(){ lg("FMOD5_System_SetUserData"); return 0; }
R FMOD5_System_UnloadPlugin(){ lg("FMOD5_System_UnloadPlugin"); return 0; }
R FMOD5_System_UnlockDSP(){ lg("FMOD5_System_UnlockDSP"); return 0; }
R FMOD5_System_Update(){ lg("FMOD5_System_Update"); return 0; }
R FMOD5_Thread_SetAttributes(){ lg("FMOD5_Thread_SetAttributes"); return 0; }
R FMOD_CREATECOMPRESSEDSAMPLE(){ lg("FMOD_CREATECOMPRESSEDSAMPLE"); return 0; }
R FMOD_OPENMEMORY_POINT(){ lg("FMOD_OPENMEMORY_POINT"); return 0; }
R FMOD_OUTPUT_NOSOUND(){ lg("FMOD_OUTPUT_NOSOUND"); return 0; }
R FMOD_REVERB_PROPERTIES(){ lg("FMOD_REVERB_PROPERTIES"); return 0; }
R FMOD_Studio_Bank_GetBusCount(){ lg("FMOD_Studio_Bank_GetBusCount"); return 0; }
R FMOD_Studio_Bank_GetBusList(){ lg("FMOD_Studio_Bank_GetBusList"); return 0; }
R FMOD_Studio_Bank_GetEventCount(){ lg("FMOD_Studio_Bank_GetEventCount"); return 0; }
R FMOD_Studio_Bank_GetEventList(){ lg("FMOD_Studio_Bank_GetEventList"); return 0; }
R FMOD_Studio_Bank_GetID(){ lg("FMOD_Studio_Bank_GetID"); return 0; }
R FMOD_Studio_Bank_GetLoadingState(void* a, int* st){ lg("FMOD_Studio_Bank_GetLoadingState"); if(st) *st=3; return 0; }
R FMOD_Studio_Bank_GetPath(){ lg("FMOD_Studio_Bank_GetPath"); return 0; }
R FMOD_Studio_Bank_GetSampleLoadingState(void* a, int* st){ lg("FMOD_Studio_Bank_GetSampleLoadingState"); if(st) *st=3; return 0; }
R FMOD_Studio_Bank_GetStringCount(){ lg("FMOD_Studio_Bank_GetStringCount"); return 0; }
R FMOD_Studio_Bank_GetStringInfo(){ lg("FMOD_Studio_Bank_GetStringInfo"); return 0; }
R FMOD_Studio_Bank_GetUserData(){ lg("FMOD_Studio_Bank_GetUserData"); return 0; }
R FMOD_Studio_Bank_GetVCACount(){ lg("FMOD_Studio_Bank_GetVCACount"); return 0; }
R FMOD_Studio_Bank_GetVCAList(){ lg("FMOD_Studio_Bank_GetVCAList"); return 0; }
int FMOD_Studio_Bank_IsValid(void* a){ return 1; }
R FMOD_Studio_Bank_LoadSampleData(){ lg("FMOD_Studio_Bank_LoadSampleData"); return 0; }
R FMOD_Studio_Bank_SetUserData(){ lg("FMOD_Studio_Bank_SetUserData"); return 0; }
R FMOD_Studio_Bank_Unload(){ lg("FMOD_Studio_Bank_Unload"); return 0; }
R FMOD_Studio_Bank_UnloadSampleData(){ lg("FMOD_Studio_Bank_UnloadSampleData"); return 0; }
R FMOD_Studio_Bus_GetChannelGroup(){ lg("FMOD_Studio_Bus_GetChannelGroup"); return 0; }
R FMOD_Studio_Bus_GetCPUUsage(){ lg("FMOD_Studio_Bus_GetCPUUsage"); return 0; }
R FMOD_Studio_Bus_GetID(){ lg("FMOD_Studio_Bus_GetID"); return 0; }
R FMOD_Studio_Bus_GetMemoryUsage(){ lg("FMOD_Studio_Bus_GetMemoryUsage"); return 0; }
R FMOD_Studio_Bus_GetMute(){ lg("FMOD_Studio_Bus_GetMute"); return 0; }
R FMOD_Studio_Bus_GetPath(){ lg("FMOD_Studio_Bus_GetPath"); return 0; }
R FMOD_Studio_Bus_GetPaused(){ lg("FMOD_Studio_Bus_GetPaused"); return 0; }
R FMOD_Studio_Bus_GetPortIndex(){ lg("FMOD_Studio_Bus_GetPortIndex"); return 0; }
R FMOD_Studio_Bus_GetVolume(){ lg("FMOD_Studio_Bus_GetVolume"); return 0; }
int FMOD_Studio_Bus_IsValid(void* a){ return 1; }
R FMOD_Studio_Bus_LockChannelGroup(){ lg("FMOD_Studio_Bus_LockChannelGroup"); return 0; }
R FMOD_Studio_Bus_SetMute(){ lg("FMOD_Studio_Bus_SetMute"); return 0; }
R FMOD_Studio_Bus_SetPaused(){ lg("FMOD_Studio_Bus_SetPaused"); return 0; }
R FMOD_Studio_Bus_SetPortIndex(){ lg("FMOD_Studio_Bus_SetPortIndex"); return 0; }
R FMOD_Studio_Bus_SetVolume(){ lg("FMOD_Studio_Bus_SetVolume"); return 0; }
R FMOD_Studio_Bus_StopAllEvents(){ lg("FMOD_Studio_Bus_StopAllEvents"); return 0; }
R FMOD_Studio_Bus_UnlockChannelGroup(){ lg("FMOD_Studio_Bus_UnlockChannelGroup"); return 0; }
R FMOD_Studio_CommandReplay_GetCommandAtTime(){ lg("FMOD_Studio_CommandReplay_GetCommandAtTime"); return 0; }
R FMOD_Studio_CommandReplay_GetCommandCount(){ lg("FMOD_Studio_CommandReplay_GetCommandCount"); return 0; }
R FMOD_Studio_CommandReplay_GetCommandInfo(){ lg("FMOD_Studio_CommandReplay_GetCommandInfo"); return 0; }
R FMOD_Studio_CommandReplay_GetCommandString(){ lg("FMOD_Studio_CommandReplay_GetCommandString"); return 0; }
R FMOD_Studio_CommandReplay_GetCurrentCommand(){ lg("FMOD_Studio_CommandReplay_GetCurrentCommand"); return 0; }
R FMOD_Studio_CommandReplay_GetLength(){ lg("FMOD_Studio_CommandReplay_GetLength"); return 0; }
R FMOD_Studio_CommandReplay_GetPaused(){ lg("FMOD_Studio_CommandReplay_GetPaused"); return 0; }
R FMOD_Studio_CommandReplay_GetPlaybackState(void* a, int* st){ lg("FMOD_Studio_CommandReplay_GetPlaybackState"); if(st) *st=2; return 0; }
R FMOD_Studio_CommandReplay_GetSystem(){ lg("FMOD_Studio_CommandReplay_GetSystem"); return 0; }
R FMOD_Studio_CommandReplay_GetUserData(){ lg("FMOD_Studio_CommandReplay_GetUserData"); return 0; }
int FMOD_Studio_CommandReplay_IsValid(void* a){ return 1; }
R FMOD_Studio_CommandReplay_Release(){ lg("FMOD_Studio_CommandReplay_Release"); return 0; }
R FMOD_Studio_CommandReplay_SeekToCommand(){ lg("FMOD_Studio_CommandReplay_SeekToCommand"); return 0; }
R FMOD_Studio_CommandReplay_SeekToTime(){ lg("FMOD_Studio_CommandReplay_SeekToTime"); return 0; }
R FMOD_Studio_CommandReplay_SetBankPath(){ lg("FMOD_Studio_CommandReplay_SetBankPath"); return 0; }
R FMOD_Studio_CommandReplay_SetCreateInstanceCallback(){ lg("FMOD_Studio_CommandReplay_SetCreateInstanceCallback"); return 0; }
R FMOD_Studio_CommandReplay_SetFrameCallback(){ lg("FMOD_Studio_CommandReplay_SetFrameCallback"); return 0; }
R FMOD_Studio_CommandReplay_SetLoadBankCallback(){ lg("FMOD_Studio_CommandReplay_SetLoadBankCallback"); return 0; }
R FMOD_Studio_CommandReplay_SetPaused(){ lg("FMOD_Studio_CommandReplay_SetPaused"); return 0; }
R FMOD_Studio_CommandReplay_SetUserData(){ lg("FMOD_Studio_CommandReplay_SetUserData"); return 0; }
R FMOD_Studio_CommandReplay_Start(){ lg("FMOD_Studio_CommandReplay_Start"); return 0; }
R FMOD_Studio_CommandReplay_Stop(){ lg("FMOD_Studio_CommandReplay_Stop"); return 0; }
R FMOD_Studio_EventDescription_CreateInstance(){ lg("FMOD_Studio_EventDescription_CreateInstance"); return 0; }
R FMOD_Studio_EventDescription_GetID(){ lg("FMOD_Studio_EventDescription_GetID"); return 0; }
R FMOD_Studio_EventDescription_GetInstanceCount(){ lg("FMOD_Studio_EventDescription_GetInstanceCount"); return 0; }
R FMOD_Studio_EventDescription_GetInstanceList(){ lg("FMOD_Studio_EventDescription_GetInstanceList"); return 0; }
R FMOD_Studio_EventDescription_GetLength(){ lg("FMOD_Studio_EventDescription_GetLength"); return 0; }
R FMOD_Studio_EventDescription_GetMinMaxDistance(){ lg("FMOD_Studio_EventDescription_GetMinMaxDistance"); return 0; }
R FMOD_Studio_EventDescription_GetParameterDescriptionByID(){ lg("FMOD_Studio_EventDescription_GetParameterDescriptionByID"); return 0; }
R FMOD_Studio_EventDescription_GetParameterDescriptionByIndex(){ lg("FMOD_Studio_EventDescription_GetParameterDescriptionByIndex"); return 0; }
R FMOD_Studio_EventDescription_GetParameterDescriptionByName(){ lg("FMOD_Studio_EventDescription_GetParameterDescriptionByName"); return 0; }
R FMOD_Studio_EventDescription_GetParameterDescriptionCount(){ lg("FMOD_Studio_EventDescription_GetParameterDescriptionCount"); return 0; }
R FMOD_Studio_EventDescription_GetParameterLabelByID(){ lg("FMOD_Studio_EventDescription_GetParameterLabelByID"); return 0; }
R FMOD_Studio_EventDescription_GetParameterLabelByIndex(){ lg("FMOD_Studio_EventDescription_GetParameterLabelByIndex"); return 0; }
R FMOD_Studio_EventDescription_GetParameterLabelByName(){ lg("FMOD_Studio_EventDescription_GetParameterLabelByName"); return 0; }
R FMOD_Studio_EventDescription_GetPath(){ lg("FMOD_Studio_EventDescription_GetPath"); return 0; }
R FMOD_Studio_EventDescription_GetSampleLoadingState(void* a, int* st){ lg("FMOD_Studio_EventDescription_GetSampleLoadingState"); if(st) *st=3; return 0; }
R FMOD_Studio_EventDescription_GetSoundSize(){ lg("FMOD_Studio_EventDescription_GetSoundSize"); return 0; }
R FMOD_Studio_EventDescription_GetUserData(){ lg("FMOD_Studio_EventDescription_GetUserData"); return 0; }
R FMOD_Studio_EventDescription_GetUserProperty(){ lg("FMOD_Studio_EventDescription_GetUserProperty"); return 0; }
R FMOD_Studio_EventDescription_GetUserPropertyByIndex(){ lg("FMOD_Studio_EventDescription_GetUserPropertyByIndex"); return 0; }
R FMOD_Studio_EventDescription_GetUserPropertyCount(){ lg("FMOD_Studio_EventDescription_GetUserPropertyCount"); return 0; }
R FMOD_Studio_EventDescription_HasSustainPoint(){ lg("FMOD_Studio_EventDescription_HasSustainPoint"); return 0; }
R FMOD_Studio_EventDescription_Is3D(){ lg("FMOD_Studio_EventDescription_Is3D"); return 0; }
R FMOD_Studio_EventDescription_IsDopplerEnabled(){ lg("FMOD_Studio_EventDescription_IsDopplerEnabled"); return 0; }
R FMOD_Studio_EventDescription_IsOneshot(){ lg("FMOD_Studio_EventDescription_IsOneshot"); return 0; }
R FMOD_Studio_EventDescription_IsSnapshot(){ lg("FMOD_Studio_EventDescription_IsSnapshot"); return 0; }
R FMOD_Studio_EventDescription_IsStream(){ lg("FMOD_Studio_EventDescription_IsStream"); return 0; }
int FMOD_Studio_EventDescription_IsValid(void* a){ return 1; }
R FMOD_Studio_EventDescription_LoadSampleData(){ lg("FMOD_Studio_EventDescription_LoadSampleData"); return 0; }
R FMOD_Studio_EventDescription_ReleaseAllInstances(){ lg("FMOD_Studio_EventDescription_ReleaseAllInstances"); return 0; }
R FMOD_Studio_EventDescription_SetCallback(){ lg("FMOD_Studio_EventDescription_SetCallback"); return 0; }
R FMOD_Studio_EventDescription_SetUserData(){ lg("FMOD_Studio_EventDescription_SetUserData"); return 0; }
R FMOD_Studio_EventDescription_UnloadSampleData(){ lg("FMOD_Studio_EventDescription_UnloadSampleData"); return 0; }
R FMOD_Studio_EventInstance_Get3DAttributes(){ lg("FMOD_Studio_EventInstance_Get3DAttributes"); return 0; }
R FMOD_Studio_EventInstance_GetChannelGroup(){ lg("FMOD_Studio_EventInstance_GetChannelGroup"); return 0; }
R FMOD_Studio_EventInstance_GetCPUUsage(){ lg("FMOD_Studio_EventInstance_GetCPUUsage"); return 0; }
R FMOD_Studio_EventInstance_GetDescription(){ lg("FMOD_Studio_EventInstance_GetDescription"); return 0; }
R FMOD_Studio_EventInstance_GetListenerMask(){ lg("FMOD_Studio_EventInstance_GetListenerMask"); return 0; }
R FMOD_Studio_EventInstance_GetMemoryUsage(){ lg("FMOD_Studio_EventInstance_GetMemoryUsage"); return 0; }
R FMOD_Studio_EventInstance_GetMinMaxDistance(){ lg("FMOD_Studio_EventInstance_GetMinMaxDistance"); return 0; }
R FMOD_Studio_EventInstance_GetParameterByID(){ lg("FMOD_Studio_EventInstance_GetParameterByID"); return 0; }
R FMOD_Studio_EventInstance_GetParameterByName(){ lg("FMOD_Studio_EventInstance_GetParameterByName"); return 0; }
R FMOD_Studio_EventInstance_GetPaused(){ lg("FMOD_Studio_EventInstance_GetPaused"); return 0; }
R FMOD_Studio_EventInstance_GetPitch(){ lg("FMOD_Studio_EventInstance_GetPitch"); return 0; }
R FMOD_Studio_EventInstance_GetPlaybackState(void* a, int* st){ lg("FMOD_Studio_EventInstance_GetPlaybackState"); if(st) *st=2; return 0; }
R FMOD_Studio_EventInstance_GetProperty(){ lg("FMOD_Studio_EventInstance_GetProperty"); return 0; }
R FMOD_Studio_EventInstance_GetReverbLevel(){ lg("FMOD_Studio_EventInstance_GetReverbLevel"); return 0; }
R FMOD_Studio_EventInstance_GetTimelinePosition(){ lg("FMOD_Studio_EventInstance_GetTimelinePosition"); return 0; }
R FMOD_Studio_EventInstance_GetUserData(){ lg("FMOD_Studio_EventInstance_GetUserData"); return 0; }
R FMOD_Studio_EventInstance_GetVolume(){ lg("FMOD_Studio_EventInstance_GetVolume"); return 0; }
int FMOD_Studio_EventInstance_IsValid(void* a){ return 1; }
R FMOD_Studio_EventInstance_IsVirtual(){ lg("FMOD_Studio_EventInstance_IsVirtual"); return 0; }
R FMOD_Studio_EventInstance_KeyOff(){ lg("FMOD_Studio_EventInstance_KeyOff"); return 0; }
R FMOD_Studio_EventInstance_Release(){ lg("FMOD_Studio_EventInstance_Release"); return 0; }
R FMOD_Studio_EventInstance_Set3DAttributes(){ lg("FMOD_Studio_EventInstance_Set3DAttributes"); return 0; }
R FMOD_Studio_EventInstance_SetCallback(){ lg("FMOD_Studio_EventInstance_SetCallback"); return 0; }
R FMOD_Studio_EventInstance_SetListenerMask(){ lg("FMOD_Studio_EventInstance_SetListenerMask"); return 0; }
R FMOD_Studio_EventInstance_SetParameterByID(){ lg("FMOD_Studio_EventInstance_SetParameterByID"); return 0; }
R FMOD_Studio_EventInstance_SetParameterByIDWithLabel(){ lg("FMOD_Studio_EventInstance_SetParameterByIDWithLabel"); return 0; }
R FMOD_Studio_EventInstance_SetParameterByName(){ lg("FMOD_Studio_EventInstance_SetParameterByName"); return 0; }
R FMOD_Studio_EventInstance_SetParameterByNameWithLabel(){ lg("FMOD_Studio_EventInstance_SetParameterByNameWithLabel"); return 0; }
R FMOD_Studio_EventInstance_SetParametersByIDs(){ lg("FMOD_Studio_EventInstance_SetParametersByIDs"); return 0; }
R FMOD_Studio_EventInstance_SetPaused(){ lg("FMOD_Studio_EventInstance_SetPaused"); return 0; }
R FMOD_Studio_EventInstance_SetPitch(){ lg("FMOD_Studio_EventInstance_SetPitch"); return 0; }
R FMOD_Studio_EventInstance_SetProperty(){ lg("FMOD_Studio_EventInstance_SetProperty"); return 0; }
R FMOD_Studio_EventInstance_SetReverbLevel(){ lg("FMOD_Studio_EventInstance_SetReverbLevel"); return 0; }
R FMOD_Studio_EventInstance_SetTimelinePosition(){ lg("FMOD_Studio_EventInstance_SetTimelinePosition"); return 0; }
R FMOD_Studio_EventInstance_SetUserData(){ lg("FMOD_Studio_EventInstance_SetUserData"); return 0; }
R FMOD_Studio_EventInstance_SetVolume(){ lg("FMOD_Studio_EventInstance_SetVolume"); return 0; }
R FMOD_Studio_EventInstance_Start(){ lg("FMOD_Studio_EventInstance_Start"); return 0; }
R FMOD_Studio_EventInstance_Stop(){ lg("FMOD_Studio_EventInstance_Stop"); return 0; }
R FMOD_Studio_ParseID(){ lg("FMOD_Studio_ParseID"); return 0; }
R FMOD_Studio_System_Create(){ lg("FMOD_Studio_System_Create"); return 0; }
R FMOD_Studio_System_FlushCommands(){ lg("FMOD_Studio_System_FlushCommands"); return 0; }
R FMOD_Studio_System_FlushSampleLoading(){ lg("FMOD_Studio_System_FlushSampleLoading"); return 0; }
R FMOD_Studio_System_GetAdvancedSettings(){ lg("FMOD_Studio_System_GetAdvancedSettings"); return 0; }
R FMOD_Studio_System_GetBank(){ lg("FMOD_Studio_System_GetBank"); return 0; }
R FMOD_Studio_System_GetBankByID(){ lg("FMOD_Studio_System_GetBankByID"); return 0; }
R FMOD_Studio_System_GetBankCount(){ lg("FMOD_Studio_System_GetBankCount"); return 0; }
R FMOD_Studio_System_GetBankList(){ lg("FMOD_Studio_System_GetBankList"); return 0; }
R FMOD_Studio_System_GetBufferUsage(){ lg("FMOD_Studio_System_GetBufferUsage"); return 0; }
R FMOD_Studio_System_GetBus(){ lg("FMOD_Studio_System_GetBus"); return 0; }
R FMOD_Studio_System_GetBusByID(){ lg("FMOD_Studio_System_GetBusByID"); return 0; }
R FMOD_Studio_System_GetCoreSystem(){ lg("FMOD_Studio_System_GetCoreSystem"); return 0; }
R FMOD_Studio_System_GetCPUUsage(){ lg("FMOD_Studio_System_GetCPUUsage"); return 0; }
R FMOD_Studio_System_GetEvent(){ lg("FMOD_Studio_System_GetEvent"); return 0; }
R FMOD_Studio_System_GetEventByID(){ lg("FMOD_Studio_System_GetEventByID"); return 0; }
R FMOD_Studio_System_GetListenerAttributes(){ lg("FMOD_Studio_System_GetListenerAttributes"); return 0; }
R FMOD_Studio_System_GetListenerWeight(){ lg("FMOD_Studio_System_GetListenerWeight"); return 0; }
R FMOD_Studio_System_GetMemoryUsage(){ lg("FMOD_Studio_System_GetMemoryUsage"); return 0; }
R FMOD_Studio_System_GetNumListeners(){ lg("FMOD_Studio_System_GetNumListeners"); return 0; }
R FMOD_Studio_System_GetParameterByID(){ lg("FMOD_Studio_System_GetParameterByID"); return 0; }
R FMOD_Studio_System_GetParameterByName(){ lg("FMOD_Studio_System_GetParameterByName"); return 0; }
R FMOD_Studio_System_GetParameterDescriptionByID(){ lg("FMOD_Studio_System_GetParameterDescriptionByID"); return 0; }
R FMOD_Studio_System_GetParameterDescriptionByName(){ lg("FMOD_Studio_System_GetParameterDescriptionByName"); return 0; }
R FMOD_Studio_System_GetParameterDescriptionCount(){ lg("FMOD_Studio_System_GetParameterDescriptionCount"); return 0; }
R FMOD_Studio_System_GetParameterDescriptionList(){ lg("FMOD_Studio_System_GetParameterDescriptionList"); return 0; }
R FMOD_Studio_System_GetParameterLabelByID(){ lg("FMOD_Studio_System_GetParameterLabelByID"); return 0; }
R FMOD_Studio_System_GetParameterLabelByName(){ lg("FMOD_Studio_System_GetParameterLabelByName"); return 0; }
R FMOD_Studio_System_GetSoundInfo(){ lg("FMOD_Studio_System_GetSoundInfo"); return 0; }
R FMOD_Studio_System_GetUserData(){ lg("FMOD_Studio_System_GetUserData"); return 0; }
R FMOD_Studio_System_GetVCA(){ lg("FMOD_Studio_System_GetVCA"); return 0; }
R FMOD_Studio_System_GetVCAByID(){ lg("FMOD_Studio_System_GetVCAByID"); return 0; }
R FMOD_Studio_System_Initialize(){ lg("FMOD_Studio_System_Initialize"); return 0; }
int FMOD_Studio_System_IsValid(void* a){ return 1; }
R FMOD_Studio_System_LoadBankCustom(){ lg("FMOD_Studio_System_LoadBankCustom"); return 0; }
R FMOD_Studio_System_LoadBankFile(){ lg("FMOD_Studio_System_LoadBankFile"); return 0; }
R FMOD_Studio_System_LoadBankMemory(){ lg("FMOD_Studio_System_LoadBankMemory"); return 0; }
R FMOD_Studio_System_LoadCommandReplay(){ lg("FMOD_Studio_System_LoadCommandReplay"); return 0; }
R FMOD_Studio_System_LookupID(){ lg("FMOD_Studio_System_LookupID"); return 0; }
R FMOD_Studio_System_LookupPath(){ lg("FMOD_Studio_System_LookupPath"); return 0; }
R FMOD_Studio_System_Release(){ lg("FMOD_Studio_System_Release"); return 0; }
R FMOD_Studio_System_ResetBufferUsage(){ lg("FMOD_Studio_System_ResetBufferUsage"); return 0; }
R FMOD_Studio_System_SetAdvancedSettings(){ lg("FMOD_Studio_System_SetAdvancedSettings"); return 0; }
R FMOD_Studio_System_SetCallback(){ lg("FMOD_Studio_System_SetCallback"); return 0; }
R FMOD_Studio_System_SetListenerAttributes(){ lg("FMOD_Studio_System_SetListenerAttributes"); return 0; }
R FMOD_Studio_System_SetListenerWeight(){ lg("FMOD_Studio_System_SetListenerWeight"); return 0; }
R FMOD_Studio_System_SetNumListeners(){ lg("FMOD_Studio_System_SetNumListeners"); return 0; }
R FMOD_Studio_System_SetParameterByID(){ lg("FMOD_Studio_System_SetParameterByID"); return 0; }
R FMOD_Studio_System_SetParameterByIDWithLabel(){ lg("FMOD_Studio_System_SetParameterByIDWithLabel"); return 0; }
R FMOD_Studio_System_SetParameterByName(){ lg("FMOD_Studio_System_SetParameterByName"); return 0; }
R FMOD_Studio_System_SetParameterByNameWithLabel(){ lg("FMOD_Studio_System_SetParameterByNameWithLabel"); return 0; }
R FMOD_Studio_System_SetParametersByIDs(){ lg("FMOD_Studio_System_SetParametersByIDs"); return 0; }
R FMOD_Studio_System_SetUserData(){ lg("FMOD_Studio_System_SetUserData"); return 0; }
R FMOD_Studio_System_StartCommandCapture(){ lg("FMOD_Studio_System_StartCommandCapture"); return 0; }
R FMOD_Studio_System_StopCommandCapture(){ lg("FMOD_Studio_System_StopCommandCapture"); return 0; }
R FMOD_Studio_System_UnloadAll(){ lg("FMOD_Studio_System_UnloadAll"); return 0; }
R FMOD_Studio_System_Update(){ lg("FMOD_Studio_System_Update"); return 0; }
R FMOD_Studio_VCA_GetID(){ lg("FMOD_Studio_VCA_GetID"); return 0; }
R FMOD_Studio_VCA_GetPath(){ lg("FMOD_Studio_VCA_GetPath"); return 0; }
R FMOD_Studio_VCA_GetVolume(){ lg("FMOD_Studio_VCA_GetVolume"); return 0; }
int FMOD_Studio_VCA_IsValid(void* a){ return 1; }
R FMOD_Studio_VCA_SetVolume(){ lg("FMOD_Studio_VCA_SetVolume"); return 0; }
