// jni_idx_stubs.gen.c — GERADO. Stub por indice do JNIEnv (loga nome + idx).
// Sob g_vmtrace (fase VM pairip) loga TODA chamada; senao so as 3 primeiras.
#include <stdio.h>
#include <stdint.h>
extern int g_vmtrace;
static intptr_t ji_0(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx0 (idx 0)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx0 (idx 0)]\n"); return 0; }
static intptr_t ji_1(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx1 (idx 1)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx1 (idx 1)]\n"); return 0; }
static intptr_t ji_2(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx2 (idx 2)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx2 (idx 2)]\n"); return 0; }
static intptr_t ji_3(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx3 (idx 3)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx3 (idx 3)]\n"); return 0; }
static intptr_t ji_4(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetVersion (idx 4)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetVersion (idx 4)]\n"); return 0; }
static intptr_t ji_5(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! DefineClass (idx 5)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv DefineClass (idx 5)]\n"); return 0; }
static intptr_t ji_6(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! FindClass (idx 6)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv FindClass (idx 6)]\n"); return 0; }
static intptr_t ji_7(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! FromReflectedMethod (idx 7)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv FromReflectedMethod (idx 7)]\n"); return 0; }
static intptr_t ji_8(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! FromReflectedField (idx 8)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv FromReflectedField (idx 8)]\n"); return 0; }
static intptr_t ji_9(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ToReflectedMethod (idx 9)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ToReflectedMethod (idx 9)]\n"); return 0; }
static intptr_t ji_10(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetSuperclass (idx 10)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetSuperclass (idx 10)]\n"); return 0; }
static intptr_t ji_11(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! IsAssignableFrom (idx 11)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv IsAssignableFrom (idx 11)]\n"); return 0; }
static intptr_t ji_12(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ToReflectedField (idx 12)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ToReflectedField (idx 12)]\n"); return 0; }
static intptr_t ji_13(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! Throw (idx 13)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv Throw (idx 13)]\n"); return 0; }
static intptr_t ji_14(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ThrowNew (idx 14)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ThrowNew (idx 14)]\n"); return 0; }
static intptr_t ji_15(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ExceptionOccurred (idx 15)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ExceptionOccurred (idx 15)]\n"); return 0; }
static intptr_t ji_16(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ExceptionDescribe (idx 16)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ExceptionDescribe (idx 16)]\n"); return 0; }
static intptr_t ji_17(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ExceptionClear (idx 17)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ExceptionClear (idx 17)]\n"); return 0; }
static intptr_t ji_18(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! FatalError (idx 18)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv FatalError (idx 18)]\n"); return 0; }
static intptr_t ji_19(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! PushLocalFrame (idx 19)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv PushLocalFrame (idx 19)]\n"); return 0; }
static intptr_t ji_20(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! PopLocalFrame (idx 20)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv PopLocalFrame (idx 20)]\n"); return 0; }
static intptr_t ji_21(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewGlobalRef (idx 21)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewGlobalRef (idx 21)]\n"); return 0; }
static intptr_t ji_22(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! DeleteGlobalRef (idx 22)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv DeleteGlobalRef (idx 22)]\n"); return 0; }
static intptr_t ji_23(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! DeleteLocalRef (idx 23)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv DeleteLocalRef (idx 23)]\n"); return 0; }
static intptr_t ji_24(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! IsSameObject (idx 24)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv IsSameObject (idx 24)]\n"); return 0; }
static intptr_t ji_25(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewLocalRef (idx 25)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewLocalRef (idx 25)]\n"); return 0; }
static intptr_t ji_26(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! EnsureLocalCapacity (idx 26)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv EnsureLocalCapacity (idx 26)]\n"); return 0; }
static intptr_t ji_27(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! AllocObject (idx 27)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv AllocObject (idx 27)]\n"); return 0; }
static intptr_t ji_28(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewObject (idx 28)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewObject (idx 28)]\n"); return 0; }
static intptr_t ji_29(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewObjectV (idx 29)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewObjectV (idx 29)]\n"); return 0; }
static intptr_t ji_30(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewObjectA (idx 30)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewObjectA (idx 30)]\n"); return 0; }
static intptr_t ji_31(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetObjectClass (idx 31)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetObjectClass (idx 31)]\n"); return 0; }
static intptr_t ji_32(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! IsInstanceOf (idx 32)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv IsInstanceOf (idx 32)]\n"); return 0; }
static intptr_t ji_33(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetMethodID (idx 33)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetMethodID (idx 33)]\n"); return 0; }
static intptr_t ji_34(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallObjectMethod (idx 34)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallObjectMethod (idx 34)]\n"); return 0; }
static intptr_t ji_35(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallObjectMethodV (idx 35)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallObjectMethodV (idx 35)]\n"); return 0; }
static intptr_t ji_36(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallObjectMethodA (idx 36)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallObjectMethodA (idx 36)]\n"); return 0; }
static intptr_t ji_37(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallBooleanMethod (idx 37)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallBooleanMethod (idx 37)]\n"); return 0; }
static intptr_t ji_38(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallBooleanMethodV (idx 38)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallBooleanMethodV (idx 38)]\n"); return 0; }
static intptr_t ji_39(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallBooleanMethodA (idx 39)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallBooleanMethodA (idx 39)]\n"); return 0; }
static intptr_t ji_40(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallByteMethod (idx 40)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallByteMethod (idx 40)]\n"); return 0; }
static intptr_t ji_41(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallByteMethodV (idx 41)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallByteMethodV (idx 41)]\n"); return 0; }
static intptr_t ji_42(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallByteMethodA (idx 42)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallByteMethodA (idx 42)]\n"); return 0; }
static intptr_t ji_43(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallCharMethod (idx 43)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallCharMethod (idx 43)]\n"); return 0; }
static intptr_t ji_44(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallCharMethodV (idx 44)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallCharMethodV (idx 44)]\n"); return 0; }
static intptr_t ji_45(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallCharMethodA (idx 45)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallCharMethodA (idx 45)]\n"); return 0; }
static intptr_t ji_46(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallShortMethod (idx 46)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallShortMethod (idx 46)]\n"); return 0; }
static intptr_t ji_47(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallShortMethodV (idx 47)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallShortMethodV (idx 47)]\n"); return 0; }
static intptr_t ji_48(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallShortMethodA (idx 48)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallShortMethodA (idx 48)]\n"); return 0; }
static intptr_t ji_49(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallIntMethod (idx 49)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallIntMethod (idx 49)]\n"); return 0; }
static intptr_t ji_50(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallIntMethodV (idx 50)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallIntMethodV (idx 50)]\n"); return 0; }
static intptr_t ji_51(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallIntMethodA (idx 51)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallIntMethodA (idx 51)]\n"); return 0; }
static intptr_t ji_52(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallLongMethod (idx 52)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallLongMethod (idx 52)]\n"); return 0; }
static intptr_t ji_53(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallLongMethodV (idx 53)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallLongMethodV (idx 53)]\n"); return 0; }
static intptr_t ji_54(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallLongMethodA (idx 54)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallLongMethodA (idx 54)]\n"); return 0; }
static intptr_t ji_55(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallFloatMethod (idx 55)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallFloatMethod (idx 55)]\n"); return 0; }
static intptr_t ji_56(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallFloatMethodV (idx 56)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallFloatMethodV (idx 56)]\n"); return 0; }
static intptr_t ji_57(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallFloatMethodA (idx 57)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallFloatMethodA (idx 57)]\n"); return 0; }
static intptr_t ji_58(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallDoubleMethod (idx 58)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallDoubleMethod (idx 58)]\n"); return 0; }
static intptr_t ji_59(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallDoubleMethodV (idx 59)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallDoubleMethodV (idx 59)]\n"); return 0; }
static intptr_t ji_60(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallDoubleMethodA (idx 60)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallDoubleMethodA (idx 60)]\n"); return 0; }
static intptr_t ji_61(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallVoidMethod (idx 61)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallVoidMethod (idx 61)]\n"); return 0; }
static intptr_t ji_62(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallVoidMethodV (idx 62)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallVoidMethodV (idx 62)]\n"); return 0; }
static intptr_t ji_63(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallVoidMethodA (idx 63)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallVoidMethodA (idx 63)]\n"); return 0; }
static intptr_t ji_64(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualObjectMethod (idx 64)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualObjectMethod (idx 64)]\n"); return 0; }
static intptr_t ji_65(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualObjectMethodV (idx 65)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualObjectMethodV (idx 65)]\n"); return 0; }
static intptr_t ji_66(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualObjectMethodA (idx 66)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualObjectMethodA (idx 66)]\n"); return 0; }
static intptr_t ji_67(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualBooleanMethod (idx 67)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualBooleanMethod (idx 67)]\n"); return 0; }
static intptr_t ji_68(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualBooleanMethodV (idx 68)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualBooleanMethodV (idx 68)]\n"); return 0; }
static intptr_t ji_69(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualBooleanMethodA (idx 69)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualBooleanMethodA (idx 69)]\n"); return 0; }
static intptr_t ji_70(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualByteMethod (idx 70)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualByteMethod (idx 70)]\n"); return 0; }
static intptr_t ji_71(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualByteMethodV (idx 71)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualByteMethodV (idx 71)]\n"); return 0; }
static intptr_t ji_72(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualByteMethodA (idx 72)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualByteMethodA (idx 72)]\n"); return 0; }
static intptr_t ji_73(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualCharMethod (idx 73)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualCharMethod (idx 73)]\n"); return 0; }
static intptr_t ji_74(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualCharMethodV (idx 74)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualCharMethodV (idx 74)]\n"); return 0; }
static intptr_t ji_75(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualCharMethodA (idx 75)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualCharMethodA (idx 75)]\n"); return 0; }
static intptr_t ji_76(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualShortMethod (idx 76)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualShortMethod (idx 76)]\n"); return 0; }
static intptr_t ji_77(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualShortMethodV (idx 77)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualShortMethodV (idx 77)]\n"); return 0; }
static intptr_t ji_78(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualShortMethodA (idx 78)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualShortMethodA (idx 78)]\n"); return 0; }
static intptr_t ji_79(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualIntMethod (idx 79)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualIntMethod (idx 79)]\n"); return 0; }
static intptr_t ji_80(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualIntMethodV (idx 80)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualIntMethodV (idx 80)]\n"); return 0; }
static intptr_t ji_81(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualIntMethodA (idx 81)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualIntMethodA (idx 81)]\n"); return 0; }
static intptr_t ji_82(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualLongMethod (idx 82)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualLongMethod (idx 82)]\n"); return 0; }
static intptr_t ji_83(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualLongMethodV (idx 83)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualLongMethodV (idx 83)]\n"); return 0; }
static intptr_t ji_84(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualLongMethodA (idx 84)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualLongMethodA (idx 84)]\n"); return 0; }
static intptr_t ji_85(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualFloatMethod (idx 85)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualFloatMethod (idx 85)]\n"); return 0; }
static intptr_t ji_86(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualFloatMethodV (idx 86)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualFloatMethodV (idx 86)]\n"); return 0; }
static intptr_t ji_87(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualFloatMethodA (idx 87)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualFloatMethodA (idx 87)]\n"); return 0; }
static intptr_t ji_88(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualDoubleMethod (idx 88)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualDoubleMethod (idx 88)]\n"); return 0; }
static intptr_t ji_89(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualDoubleMethodV (idx 89)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualDoubleMethodV (idx 89)]\n"); return 0; }
static intptr_t ji_90(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualDoubleMethodA (idx 90)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualDoubleMethodA (idx 90)]\n"); return 0; }
static intptr_t ji_91(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualVoidMethod (idx 91)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualVoidMethod (idx 91)]\n"); return 0; }
static intptr_t ji_92(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualVoidMethodV (idx 92)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualVoidMethodV (idx 92)]\n"); return 0; }
static intptr_t ji_93(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallNonvirtualVoidMethodA (idx 93)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallNonvirtualVoidMethodA (idx 93)]\n"); return 0; }
static intptr_t ji_94(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetFieldID (idx 94)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetFieldID (idx 94)]\n"); return 0; }
static intptr_t ji_95(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetObjectField (idx 95)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetObjectField (idx 95)]\n"); return 0; }
static intptr_t ji_96(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetBooleanField (idx 96)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetBooleanField (idx 96)]\n"); return 0; }
static intptr_t ji_97(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetByteField (idx 97)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetByteField (idx 97)]\n"); return 0; }
static intptr_t ji_98(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetCharField (idx 98)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetCharField (idx 98)]\n"); return 0; }
static intptr_t ji_99(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetShortField (idx 99)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetShortField (idx 99)]\n"); return 0; }
static intptr_t ji_100(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetIntField (idx 100)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetIntField (idx 100)]\n"); return 0; }
static intptr_t ji_101(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetLongField (idx 101)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetLongField (idx 101)]\n"); return 0; }
static intptr_t ji_102(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetFloatField (idx 102)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetFloatField (idx 102)]\n"); return 0; }
static intptr_t ji_103(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetDoubleField (idx 103)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetDoubleField (idx 103)]\n"); return 0; }
static intptr_t ji_104(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetObjectField (idx 104)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetObjectField (idx 104)]\n"); return 0; }
static intptr_t ji_105(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetBooleanField (idx 105)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetBooleanField (idx 105)]\n"); return 0; }
static intptr_t ji_106(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetByteField (idx 106)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetByteField (idx 106)]\n"); return 0; }
static intptr_t ji_107(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetCharField (idx 107)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetCharField (idx 107)]\n"); return 0; }
static intptr_t ji_108(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetShortField (idx 108)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetShortField (idx 108)]\n"); return 0; }
static intptr_t ji_109(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetIntField (idx 109)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetIntField (idx 109)]\n"); return 0; }
static intptr_t ji_110(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetLongField (idx 110)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetLongField (idx 110)]\n"); return 0; }
static intptr_t ji_111(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetFloatField (idx 111)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetFloatField (idx 111)]\n"); return 0; }
static intptr_t ji_112(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetDoubleField (idx 112)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetDoubleField (idx 112)]\n"); return 0; }
static intptr_t ji_113(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticMethodID (idx 113)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticMethodID (idx 113)]\n"); return 0; }
static intptr_t ji_114(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticObjectMethod (idx 114)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticObjectMethod (idx 114)]\n"); return 0; }
static intptr_t ji_115(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticObjectMethodV (idx 115)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticObjectMethodV (idx 115)]\n"); return 0; }
static intptr_t ji_116(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticObjectMethodA (idx 116)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticObjectMethodA (idx 116)]\n"); return 0; }
static intptr_t ji_117(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticBooleanMethod (idx 117)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticBooleanMethod (idx 117)]\n"); return 0; }
static intptr_t ji_118(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticBooleanMethodV (idx 118)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticBooleanMethodV (idx 118)]\n"); return 0; }
static intptr_t ji_119(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticBooleanMethodA (idx 119)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticBooleanMethodA (idx 119)]\n"); return 0; }
static intptr_t ji_120(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticByteMethod (idx 120)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticByteMethod (idx 120)]\n"); return 0; }
static intptr_t ji_121(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticByteMethodV (idx 121)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticByteMethodV (idx 121)]\n"); return 0; }
static intptr_t ji_122(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticByteMethodA (idx 122)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticByteMethodA (idx 122)]\n"); return 0; }
static intptr_t ji_123(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticCharMethod (idx 123)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticCharMethod (idx 123)]\n"); return 0; }
static intptr_t ji_124(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticCharMethodV (idx 124)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticCharMethodV (idx 124)]\n"); return 0; }
static intptr_t ji_125(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticCharMethodA (idx 125)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticCharMethodA (idx 125)]\n"); return 0; }
static intptr_t ji_126(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticShortMethod (idx 126)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticShortMethod (idx 126)]\n"); return 0; }
static intptr_t ji_127(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticShortMethodV (idx 127)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticShortMethodV (idx 127)]\n"); return 0; }
static intptr_t ji_128(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticShortMethodA (idx 128)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticShortMethodA (idx 128)]\n"); return 0; }
static intptr_t ji_129(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticIntMethod (idx 129)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticIntMethod (idx 129)]\n"); return 0; }
static intptr_t ji_130(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticIntMethodV (idx 130)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticIntMethodV (idx 130)]\n"); return 0; }
static intptr_t ji_131(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticIntMethodA (idx 131)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticIntMethodA (idx 131)]\n"); return 0; }
static intptr_t ji_132(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticLongMethod (idx 132)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticLongMethod (idx 132)]\n"); return 0; }
static intptr_t ji_133(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticLongMethodV (idx 133)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticLongMethodV (idx 133)]\n"); return 0; }
static intptr_t ji_134(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticLongMethodA (idx 134)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticLongMethodA (idx 134)]\n"); return 0; }
static intptr_t ji_135(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticFloatMethod (idx 135)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticFloatMethod (idx 135)]\n"); return 0; }
static intptr_t ji_136(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticFloatMethodV (idx 136)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticFloatMethodV (idx 136)]\n"); return 0; }
static intptr_t ji_137(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticFloatMethodA (idx 137)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticFloatMethodA (idx 137)]\n"); return 0; }
static intptr_t ji_138(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticDoubleMethod (idx 138)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticDoubleMethod (idx 138)]\n"); return 0; }
static intptr_t ji_139(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticDoubleMethodV (idx 139)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticDoubleMethodV (idx 139)]\n"); return 0; }
static intptr_t ji_140(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticDoubleMethodA (idx 140)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticDoubleMethodA (idx 140)]\n"); return 0; }
static intptr_t ji_141(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticVoidMethod (idx 141)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticVoidMethod (idx 141)]\n"); return 0; }
static intptr_t ji_142(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticVoidMethodV (idx 142)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticVoidMethodV (idx 142)]\n"); return 0; }
static intptr_t ji_143(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! CallStaticVoidMethodA (idx 143)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv CallStaticVoidMethodA (idx 143)]\n"); return 0; }
static intptr_t ji_144(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticFieldID (idx 144)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticFieldID (idx 144)]\n"); return 0; }
static intptr_t ji_145(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticObjectField (idx 145)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticObjectField (idx 145)]\n"); return 0; }
static intptr_t ji_146(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticBooleanField (idx 146)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticBooleanField (idx 146)]\n"); return 0; }
static intptr_t ji_147(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticByteField (idx 147)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticByteField (idx 147)]\n"); return 0; }
static intptr_t ji_148(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticCharField (idx 148)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticCharField (idx 148)]\n"); return 0; }
static intptr_t ji_149(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticShortField (idx 149)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticShortField (idx 149)]\n"); return 0; }
static intptr_t ji_150(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticIntField (idx 150)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticIntField (idx 150)]\n"); return 0; }
static intptr_t ji_151(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticLongField (idx 151)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticLongField (idx 151)]\n"); return 0; }
static intptr_t ji_152(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticFloatField (idx 152)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticFloatField (idx 152)]\n"); return 0; }
static intptr_t ji_153(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStaticDoubleField (idx 153)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStaticDoubleField (idx 153)]\n"); return 0; }
static intptr_t ji_154(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticObjectField (idx 154)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticObjectField (idx 154)]\n"); return 0; }
static intptr_t ji_155(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticBooleanField (idx 155)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticBooleanField (idx 155)]\n"); return 0; }
static intptr_t ji_156(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticByteField (idx 156)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticByteField (idx 156)]\n"); return 0; }
static intptr_t ji_157(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticCharField (idx 157)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticCharField (idx 157)]\n"); return 0; }
static intptr_t ji_158(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticShortField (idx 158)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticShortField (idx 158)]\n"); return 0; }
static intptr_t ji_159(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticIntField (idx 159)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticIntField (idx 159)]\n"); return 0; }
static intptr_t ji_160(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticLongField (idx 160)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticLongField (idx 160)]\n"); return 0; }
static intptr_t ji_161(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticFloatField (idx 161)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticFloatField (idx 161)]\n"); return 0; }
static intptr_t ji_162(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetStaticDoubleField (idx 162)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetStaticDoubleField (idx 162)]\n"); return 0; }
static intptr_t ji_163(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewString (idx 163)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewString (idx 163)]\n"); return 0; }
static intptr_t ji_164(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStringLength (idx 164)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStringLength (idx 164)]\n"); return 0; }
static intptr_t ji_165(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStringChars (idx 165)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStringChars (idx 165)]\n"); return 0; }
static intptr_t ji_166(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseStringChars (idx 166)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseStringChars (idx 166)]\n"); return 0; }
static intptr_t ji_167(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewStringUTF (idx 167)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewStringUTF (idx 167)]\n"); return 0; }
static intptr_t ji_168(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStringUTFLength (idx 168)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStringUTFLength (idx 168)]\n"); return 0; }
static intptr_t ji_169(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStringUTFChars (idx 169)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStringUTFChars (idx 169)]\n"); return 0; }
static intptr_t ji_170(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseStringUTFChars (idx 170)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseStringUTFChars (idx 170)]\n"); return 0; }
static intptr_t ji_171(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetArrayLength (idx 171)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetArrayLength (idx 171)]\n"); return 0; }
static intptr_t ji_172(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewObjectArray (idx 172)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewObjectArray (idx 172)]\n"); return 0; }
static intptr_t ji_173(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetObjectArrayElement (idx 173)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetObjectArrayElement (idx 173)]\n"); return 0; }
static intptr_t ji_174(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetObjectArrayElement (idx 174)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetObjectArrayElement (idx 174)]\n"); return 0; }
static intptr_t ji_175(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewBooleanArray (idx 175)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewBooleanArray (idx 175)]\n"); return 0; }
static intptr_t ji_176(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewByteArray (idx 176)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewByteArray (idx 176)]\n"); return 0; }
static intptr_t ji_177(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewCharArray (idx 177)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewCharArray (idx 177)]\n"); return 0; }
static intptr_t ji_178(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewShortArray (idx 178)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewShortArray (idx 178)]\n"); return 0; }
static intptr_t ji_179(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewIntArray (idx 179)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewIntArray (idx 179)]\n"); return 0; }
static intptr_t ji_180(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewLongArray (idx 180)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewLongArray (idx 180)]\n"); return 0; }
static intptr_t ji_181(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewFloatArray (idx 181)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewFloatArray (idx 181)]\n"); return 0; }
static intptr_t ji_182(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewDoubleArray (idx 182)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewDoubleArray (idx 182)]\n"); return 0; }
static intptr_t ji_183(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetBooleanArrayElements (idx 183)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetBooleanArrayElements (idx 183)]\n"); return 0; }
static intptr_t ji_184(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetByteArrayElements (idx 184)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetByteArrayElements (idx 184)]\n"); return 0; }
static intptr_t ji_185(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetCharArrayElements (idx 185)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetCharArrayElements (idx 185)]\n"); return 0; }
static intptr_t ji_186(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetShortArrayElements (idx 186)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetShortArrayElements (idx 186)]\n"); return 0; }
static intptr_t ji_187(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetIntArrayElements (idx 187)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetIntArrayElements (idx 187)]\n"); return 0; }
static intptr_t ji_188(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetLongArrayElements (idx 188)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetLongArrayElements (idx 188)]\n"); return 0; }
static intptr_t ji_189(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetFloatArrayElements (idx 189)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetFloatArrayElements (idx 189)]\n"); return 0; }
static intptr_t ji_190(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetDoubleArrayElements (idx 190)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetDoubleArrayElements (idx 190)]\n"); return 0; }
static intptr_t ji_191(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseBooleanArrayElements (idx 191)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseBooleanArrayElements (idx 191)]\n"); return 0; }
static intptr_t ji_192(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseByteArrayElements (idx 192)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseByteArrayElements (idx 192)]\n"); return 0; }
static intptr_t ji_193(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseCharArrayElements (idx 193)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseCharArrayElements (idx 193)]\n"); return 0; }
static intptr_t ji_194(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseShortArrayElements (idx 194)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseShortArrayElements (idx 194)]\n"); return 0; }
static intptr_t ji_195(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseIntArrayElements (idx 195)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseIntArrayElements (idx 195)]\n"); return 0; }
static intptr_t ji_196(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseLongArrayElements (idx 196)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseLongArrayElements (idx 196)]\n"); return 0; }
static intptr_t ji_197(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseFloatArrayElements (idx 197)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseFloatArrayElements (idx 197)]\n"); return 0; }
static intptr_t ji_198(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseDoubleArrayElements (idx 198)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseDoubleArrayElements (idx 198)]\n"); return 0; }
static intptr_t ji_199(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetBooleanArrayRegion (idx 199)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetBooleanArrayRegion (idx 199)]\n"); return 0; }
static intptr_t ji_200(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetByteArrayRegion (idx 200)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetByteArrayRegion (idx 200)]\n"); return 0; }
static intptr_t ji_201(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetCharArrayRegion (idx 201)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetCharArrayRegion (idx 201)]\n"); return 0; }
static intptr_t ji_202(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetShortArrayRegion (idx 202)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetShortArrayRegion (idx 202)]\n"); return 0; }
static intptr_t ji_203(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetIntArrayRegion (idx 203)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetIntArrayRegion (idx 203)]\n"); return 0; }
static intptr_t ji_204(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetLongArrayRegion (idx 204)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetLongArrayRegion (idx 204)]\n"); return 0; }
static intptr_t ji_205(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetFloatArrayRegion (idx 205)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetFloatArrayRegion (idx 205)]\n"); return 0; }
static intptr_t ji_206(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetDoubleArrayRegion (idx 206)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetDoubleArrayRegion (idx 206)]\n"); return 0; }
static intptr_t ji_207(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetBooleanArrayRegion (idx 207)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetBooleanArrayRegion (idx 207)]\n"); return 0; }
static intptr_t ji_208(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetByteArrayRegion (idx 208)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetByteArrayRegion (idx 208)]\n"); return 0; }
static intptr_t ji_209(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetCharArrayRegion (idx 209)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetCharArrayRegion (idx 209)]\n"); return 0; }
static intptr_t ji_210(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetShortArrayRegion (idx 210)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetShortArrayRegion (idx 210)]\n"); return 0; }
static intptr_t ji_211(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetIntArrayRegion (idx 211)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetIntArrayRegion (idx 211)]\n"); return 0; }
static intptr_t ji_212(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetLongArrayRegion (idx 212)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetLongArrayRegion (idx 212)]\n"); return 0; }
static intptr_t ji_213(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetFloatArrayRegion (idx 213)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetFloatArrayRegion (idx 213)]\n"); return 0; }
static intptr_t ji_214(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! SetDoubleArrayRegion (idx 214)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv SetDoubleArrayRegion (idx 214)]\n"); return 0; }
static intptr_t ji_215(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! RegisterNatives (idx 215)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv RegisterNatives (idx 215)]\n"); return 0; }
static intptr_t ji_216(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! UnregisterNatives (idx 216)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv UnregisterNatives (idx 216)]\n"); return 0; }
static intptr_t ji_217(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! MonitorEnter (idx 217)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv MonitorEnter (idx 217)]\n"); return 0; }
static intptr_t ji_218(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! MonitorExit (idx 218)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv MonitorExit (idx 218)]\n"); return 0; }
static intptr_t ji_219(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetJavaVM (idx 219)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetJavaVM (idx 219)]\n"); return 0; }
static intptr_t ji_220(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStringRegion (idx 220)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStringRegion (idx 220)]\n"); return 0; }
static intptr_t ji_221(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStringUTFRegion (idx 221)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStringUTFRegion (idx 221)]\n"); return 0; }
static intptr_t ji_222(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetPrimitiveArrayCritical (idx 222)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetPrimitiveArrayCritical (idx 222)]\n"); return 0; }
static intptr_t ji_223(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleasePrimitiveArrayCritical (idx 223)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleasePrimitiveArrayCritical (idx 223)]\n"); return 0; }
static intptr_t ji_224(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetStringCritical (idx 224)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetStringCritical (idx 224)]\n"); return 0; }
static intptr_t ji_225(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ReleaseStringCritical (idx 225)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ReleaseStringCritical (idx 225)]\n"); return 0; }
static intptr_t ji_226(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewWeakGlobalRef (idx 226)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewWeakGlobalRef (idx 226)]\n"); return 0; }
static intptr_t ji_227(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! DeleteWeakGlobalRef (idx 227)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv DeleteWeakGlobalRef (idx 227)]\n"); return 0; }
static intptr_t ji_228(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! ExceptionCheck (idx 228)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv ExceptionCheck (idx 228)]\n"); return 0; }
static intptr_t ji_229(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! NewDirectByteBuffer (idx 229)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv NewDirectByteBuffer (idx 229)]\n"); return 0; }
static intptr_t ji_230(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetDirectBufferAddress (idx 230)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetDirectBufferAddress (idx 230)]\n"); return 0; }
static intptr_t ji_231(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetDirectBufferCapacity (idx 231)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetDirectBufferCapacity (idx 231)]\n"); return 0; }
static intptr_t ji_232(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! GetObjectRefType (idx 232)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv GetObjectRefType (idx 232)]\n"); return 0; }
static intptr_t ji_233(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx233 (idx 233)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx233 (idx 233)]\n"); return 0; }
static intptr_t ji_234(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx234 (idx 234)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx234 (idx 234)]\n"); return 0; }
static intptr_t ji_235(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx235 (idx 235)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx235 (idx 235)]\n"); return 0; }
static intptr_t ji_236(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx236 (idx 236)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx236 (idx 236)]\n"); return 0; }
static intptr_t ji_237(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx237 (idx 237)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx237 (idx 237)]\n"); return 0; }
static intptr_t ji_238(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx238 (idx 238)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx238 (idx 238)]\n"); return 0; }
static intptr_t ji_239(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx239 (idx 239)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx239 (idx 239)]\n"); return 0; }
static intptr_t ji_240(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx240 (idx 240)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx240 (idx 240)]\n"); return 0; }
static intptr_t ji_241(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx241 (idx 241)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx241 (idx 241)]\n"); return 0; }
static intptr_t ji_242(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx242 (idx 242)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx242 (idx 242)]\n"); return 0; }
static intptr_t ji_243(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx243 (idx 243)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx243 (idx 243)]\n"); return 0; }
static intptr_t ji_244(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx244 (idx 244)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx244 (idx 244)]\n"); return 0; }
static intptr_t ji_245(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx245 (idx 245)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx245 (idx 245)]\n"); return 0; }
static intptr_t ji_246(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx246 (idx 246)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx246 (idx 246)]\n"); return 0; }
static intptr_t ji_247(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx247 (idx 247)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx247 (idx 247)]\n"); return 0; }
static intptr_t ji_248(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx248 (idx 248)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx248 (idx 248)]\n"); return 0; }
static intptr_t ji_249(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx249 (idx 249)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx249 (idx 249)]\n"); return 0; }
static intptr_t ji_250(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx250 (idx 250)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx250 (idx 250)]\n"); return 0; }
static intptr_t ji_251(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx251 (idx 251)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx251 (idx 251)]\n"); return 0; }
static intptr_t ji_252(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx252 (idx 252)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx252 (idx 252)]\n"); return 0; }
static intptr_t ji_253(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx253 (idx 253)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx253 (idx 253)]\n"); return 0; }
static intptr_t ji_254(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx254 (idx 254)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx254 (idx 254)]\n"); return 0; }
static intptr_t ji_255(void* e){ static int n=0; if(g_vmtrace) fprintf(stderr,"  [JNI! idx255 (idx 255)]\n"); else if(n++<3) fprintf(stderr,"  [JNIEnv idx255 (idx 255)]\n"); return 0; }
void jni_install_indexed(uintptr_t* vt, int n){
  if(n>0) vt[0]=(uintptr_t)ji_0;
  if(n>1) vt[1]=(uintptr_t)ji_1;
  if(n>2) vt[2]=(uintptr_t)ji_2;
  if(n>3) vt[3]=(uintptr_t)ji_3;
  if(n>4) vt[4]=(uintptr_t)ji_4;
  if(n>5) vt[5]=(uintptr_t)ji_5;
  if(n>6) vt[6]=(uintptr_t)ji_6;
  if(n>7) vt[7]=(uintptr_t)ji_7;
  if(n>8) vt[8]=(uintptr_t)ji_8;
  if(n>9) vt[9]=(uintptr_t)ji_9;
  if(n>10) vt[10]=(uintptr_t)ji_10;
  if(n>11) vt[11]=(uintptr_t)ji_11;
  if(n>12) vt[12]=(uintptr_t)ji_12;
  if(n>13) vt[13]=(uintptr_t)ji_13;
  if(n>14) vt[14]=(uintptr_t)ji_14;
  if(n>15) vt[15]=(uintptr_t)ji_15;
  if(n>16) vt[16]=(uintptr_t)ji_16;
  if(n>17) vt[17]=(uintptr_t)ji_17;
  if(n>18) vt[18]=(uintptr_t)ji_18;
  if(n>19) vt[19]=(uintptr_t)ji_19;
  if(n>20) vt[20]=(uintptr_t)ji_20;
  if(n>21) vt[21]=(uintptr_t)ji_21;
  if(n>22) vt[22]=(uintptr_t)ji_22;
  if(n>23) vt[23]=(uintptr_t)ji_23;
  if(n>24) vt[24]=(uintptr_t)ji_24;
  if(n>25) vt[25]=(uintptr_t)ji_25;
  if(n>26) vt[26]=(uintptr_t)ji_26;
  if(n>27) vt[27]=(uintptr_t)ji_27;
  if(n>28) vt[28]=(uintptr_t)ji_28;
  if(n>29) vt[29]=(uintptr_t)ji_29;
  if(n>30) vt[30]=(uintptr_t)ji_30;
  if(n>31) vt[31]=(uintptr_t)ji_31;
  if(n>32) vt[32]=(uintptr_t)ji_32;
  if(n>33) vt[33]=(uintptr_t)ji_33;
  if(n>34) vt[34]=(uintptr_t)ji_34;
  if(n>35) vt[35]=(uintptr_t)ji_35;
  if(n>36) vt[36]=(uintptr_t)ji_36;
  if(n>37) vt[37]=(uintptr_t)ji_37;
  if(n>38) vt[38]=(uintptr_t)ji_38;
  if(n>39) vt[39]=(uintptr_t)ji_39;
  if(n>40) vt[40]=(uintptr_t)ji_40;
  if(n>41) vt[41]=(uintptr_t)ji_41;
  if(n>42) vt[42]=(uintptr_t)ji_42;
  if(n>43) vt[43]=(uintptr_t)ji_43;
  if(n>44) vt[44]=(uintptr_t)ji_44;
  if(n>45) vt[45]=(uintptr_t)ji_45;
  if(n>46) vt[46]=(uintptr_t)ji_46;
  if(n>47) vt[47]=(uintptr_t)ji_47;
  if(n>48) vt[48]=(uintptr_t)ji_48;
  if(n>49) vt[49]=(uintptr_t)ji_49;
  if(n>50) vt[50]=(uintptr_t)ji_50;
  if(n>51) vt[51]=(uintptr_t)ji_51;
  if(n>52) vt[52]=(uintptr_t)ji_52;
  if(n>53) vt[53]=(uintptr_t)ji_53;
  if(n>54) vt[54]=(uintptr_t)ji_54;
  if(n>55) vt[55]=(uintptr_t)ji_55;
  if(n>56) vt[56]=(uintptr_t)ji_56;
  if(n>57) vt[57]=(uintptr_t)ji_57;
  if(n>58) vt[58]=(uintptr_t)ji_58;
  if(n>59) vt[59]=(uintptr_t)ji_59;
  if(n>60) vt[60]=(uintptr_t)ji_60;
  if(n>61) vt[61]=(uintptr_t)ji_61;
  if(n>62) vt[62]=(uintptr_t)ji_62;
  if(n>63) vt[63]=(uintptr_t)ji_63;
  if(n>64) vt[64]=(uintptr_t)ji_64;
  if(n>65) vt[65]=(uintptr_t)ji_65;
  if(n>66) vt[66]=(uintptr_t)ji_66;
  if(n>67) vt[67]=(uintptr_t)ji_67;
  if(n>68) vt[68]=(uintptr_t)ji_68;
  if(n>69) vt[69]=(uintptr_t)ji_69;
  if(n>70) vt[70]=(uintptr_t)ji_70;
  if(n>71) vt[71]=(uintptr_t)ji_71;
  if(n>72) vt[72]=(uintptr_t)ji_72;
  if(n>73) vt[73]=(uintptr_t)ji_73;
  if(n>74) vt[74]=(uintptr_t)ji_74;
  if(n>75) vt[75]=(uintptr_t)ji_75;
  if(n>76) vt[76]=(uintptr_t)ji_76;
  if(n>77) vt[77]=(uintptr_t)ji_77;
  if(n>78) vt[78]=(uintptr_t)ji_78;
  if(n>79) vt[79]=(uintptr_t)ji_79;
  if(n>80) vt[80]=(uintptr_t)ji_80;
  if(n>81) vt[81]=(uintptr_t)ji_81;
  if(n>82) vt[82]=(uintptr_t)ji_82;
  if(n>83) vt[83]=(uintptr_t)ji_83;
  if(n>84) vt[84]=(uintptr_t)ji_84;
  if(n>85) vt[85]=(uintptr_t)ji_85;
  if(n>86) vt[86]=(uintptr_t)ji_86;
  if(n>87) vt[87]=(uintptr_t)ji_87;
  if(n>88) vt[88]=(uintptr_t)ji_88;
  if(n>89) vt[89]=(uintptr_t)ji_89;
  if(n>90) vt[90]=(uintptr_t)ji_90;
  if(n>91) vt[91]=(uintptr_t)ji_91;
  if(n>92) vt[92]=(uintptr_t)ji_92;
  if(n>93) vt[93]=(uintptr_t)ji_93;
  if(n>94) vt[94]=(uintptr_t)ji_94;
  if(n>95) vt[95]=(uintptr_t)ji_95;
  if(n>96) vt[96]=(uintptr_t)ji_96;
  if(n>97) vt[97]=(uintptr_t)ji_97;
  if(n>98) vt[98]=(uintptr_t)ji_98;
  if(n>99) vt[99]=(uintptr_t)ji_99;
  if(n>100) vt[100]=(uintptr_t)ji_100;
  if(n>101) vt[101]=(uintptr_t)ji_101;
  if(n>102) vt[102]=(uintptr_t)ji_102;
  if(n>103) vt[103]=(uintptr_t)ji_103;
  if(n>104) vt[104]=(uintptr_t)ji_104;
  if(n>105) vt[105]=(uintptr_t)ji_105;
  if(n>106) vt[106]=(uintptr_t)ji_106;
  if(n>107) vt[107]=(uintptr_t)ji_107;
  if(n>108) vt[108]=(uintptr_t)ji_108;
  if(n>109) vt[109]=(uintptr_t)ji_109;
  if(n>110) vt[110]=(uintptr_t)ji_110;
  if(n>111) vt[111]=(uintptr_t)ji_111;
  if(n>112) vt[112]=(uintptr_t)ji_112;
  if(n>113) vt[113]=(uintptr_t)ji_113;
  if(n>114) vt[114]=(uintptr_t)ji_114;
  if(n>115) vt[115]=(uintptr_t)ji_115;
  if(n>116) vt[116]=(uintptr_t)ji_116;
  if(n>117) vt[117]=(uintptr_t)ji_117;
  if(n>118) vt[118]=(uintptr_t)ji_118;
  if(n>119) vt[119]=(uintptr_t)ji_119;
  if(n>120) vt[120]=(uintptr_t)ji_120;
  if(n>121) vt[121]=(uintptr_t)ji_121;
  if(n>122) vt[122]=(uintptr_t)ji_122;
  if(n>123) vt[123]=(uintptr_t)ji_123;
  if(n>124) vt[124]=(uintptr_t)ji_124;
  if(n>125) vt[125]=(uintptr_t)ji_125;
  if(n>126) vt[126]=(uintptr_t)ji_126;
  if(n>127) vt[127]=(uintptr_t)ji_127;
  if(n>128) vt[128]=(uintptr_t)ji_128;
  if(n>129) vt[129]=(uintptr_t)ji_129;
  if(n>130) vt[130]=(uintptr_t)ji_130;
  if(n>131) vt[131]=(uintptr_t)ji_131;
  if(n>132) vt[132]=(uintptr_t)ji_132;
  if(n>133) vt[133]=(uintptr_t)ji_133;
  if(n>134) vt[134]=(uintptr_t)ji_134;
  if(n>135) vt[135]=(uintptr_t)ji_135;
  if(n>136) vt[136]=(uintptr_t)ji_136;
  if(n>137) vt[137]=(uintptr_t)ji_137;
  if(n>138) vt[138]=(uintptr_t)ji_138;
  if(n>139) vt[139]=(uintptr_t)ji_139;
  if(n>140) vt[140]=(uintptr_t)ji_140;
  if(n>141) vt[141]=(uintptr_t)ji_141;
  if(n>142) vt[142]=(uintptr_t)ji_142;
  if(n>143) vt[143]=(uintptr_t)ji_143;
  if(n>144) vt[144]=(uintptr_t)ji_144;
  if(n>145) vt[145]=(uintptr_t)ji_145;
  if(n>146) vt[146]=(uintptr_t)ji_146;
  if(n>147) vt[147]=(uintptr_t)ji_147;
  if(n>148) vt[148]=(uintptr_t)ji_148;
  if(n>149) vt[149]=(uintptr_t)ji_149;
  if(n>150) vt[150]=(uintptr_t)ji_150;
  if(n>151) vt[151]=(uintptr_t)ji_151;
  if(n>152) vt[152]=(uintptr_t)ji_152;
  if(n>153) vt[153]=(uintptr_t)ji_153;
  if(n>154) vt[154]=(uintptr_t)ji_154;
  if(n>155) vt[155]=(uintptr_t)ji_155;
  if(n>156) vt[156]=(uintptr_t)ji_156;
  if(n>157) vt[157]=(uintptr_t)ji_157;
  if(n>158) vt[158]=(uintptr_t)ji_158;
  if(n>159) vt[159]=(uintptr_t)ji_159;
  if(n>160) vt[160]=(uintptr_t)ji_160;
  if(n>161) vt[161]=(uintptr_t)ji_161;
  if(n>162) vt[162]=(uintptr_t)ji_162;
  if(n>163) vt[163]=(uintptr_t)ji_163;
  if(n>164) vt[164]=(uintptr_t)ji_164;
  if(n>165) vt[165]=(uintptr_t)ji_165;
  if(n>166) vt[166]=(uintptr_t)ji_166;
  if(n>167) vt[167]=(uintptr_t)ji_167;
  if(n>168) vt[168]=(uintptr_t)ji_168;
  if(n>169) vt[169]=(uintptr_t)ji_169;
  if(n>170) vt[170]=(uintptr_t)ji_170;
  if(n>171) vt[171]=(uintptr_t)ji_171;
  if(n>172) vt[172]=(uintptr_t)ji_172;
  if(n>173) vt[173]=(uintptr_t)ji_173;
  if(n>174) vt[174]=(uintptr_t)ji_174;
  if(n>175) vt[175]=(uintptr_t)ji_175;
  if(n>176) vt[176]=(uintptr_t)ji_176;
  if(n>177) vt[177]=(uintptr_t)ji_177;
  if(n>178) vt[178]=(uintptr_t)ji_178;
  if(n>179) vt[179]=(uintptr_t)ji_179;
  if(n>180) vt[180]=(uintptr_t)ji_180;
  if(n>181) vt[181]=(uintptr_t)ji_181;
  if(n>182) vt[182]=(uintptr_t)ji_182;
  if(n>183) vt[183]=(uintptr_t)ji_183;
  if(n>184) vt[184]=(uintptr_t)ji_184;
  if(n>185) vt[185]=(uintptr_t)ji_185;
  if(n>186) vt[186]=(uintptr_t)ji_186;
  if(n>187) vt[187]=(uintptr_t)ji_187;
  if(n>188) vt[188]=(uintptr_t)ji_188;
  if(n>189) vt[189]=(uintptr_t)ji_189;
  if(n>190) vt[190]=(uintptr_t)ji_190;
  if(n>191) vt[191]=(uintptr_t)ji_191;
  if(n>192) vt[192]=(uintptr_t)ji_192;
  if(n>193) vt[193]=(uintptr_t)ji_193;
  if(n>194) vt[194]=(uintptr_t)ji_194;
  if(n>195) vt[195]=(uintptr_t)ji_195;
  if(n>196) vt[196]=(uintptr_t)ji_196;
  if(n>197) vt[197]=(uintptr_t)ji_197;
  if(n>198) vt[198]=(uintptr_t)ji_198;
  if(n>199) vt[199]=(uintptr_t)ji_199;
  if(n>200) vt[200]=(uintptr_t)ji_200;
  if(n>201) vt[201]=(uintptr_t)ji_201;
  if(n>202) vt[202]=(uintptr_t)ji_202;
  if(n>203) vt[203]=(uintptr_t)ji_203;
  if(n>204) vt[204]=(uintptr_t)ji_204;
  if(n>205) vt[205]=(uintptr_t)ji_205;
  if(n>206) vt[206]=(uintptr_t)ji_206;
  if(n>207) vt[207]=(uintptr_t)ji_207;
  if(n>208) vt[208]=(uintptr_t)ji_208;
  if(n>209) vt[209]=(uintptr_t)ji_209;
  if(n>210) vt[210]=(uintptr_t)ji_210;
  if(n>211) vt[211]=(uintptr_t)ji_211;
  if(n>212) vt[212]=(uintptr_t)ji_212;
  if(n>213) vt[213]=(uintptr_t)ji_213;
  if(n>214) vt[214]=(uintptr_t)ji_214;
  if(n>215) vt[215]=(uintptr_t)ji_215;
  if(n>216) vt[216]=(uintptr_t)ji_216;
  if(n>217) vt[217]=(uintptr_t)ji_217;
  if(n>218) vt[218]=(uintptr_t)ji_218;
  if(n>219) vt[219]=(uintptr_t)ji_219;
  if(n>220) vt[220]=(uintptr_t)ji_220;
  if(n>221) vt[221]=(uintptr_t)ji_221;
  if(n>222) vt[222]=(uintptr_t)ji_222;
  if(n>223) vt[223]=(uintptr_t)ji_223;
  if(n>224) vt[224]=(uintptr_t)ji_224;
  if(n>225) vt[225]=(uintptr_t)ji_225;
  if(n>226) vt[226]=(uintptr_t)ji_226;
  if(n>227) vt[227]=(uintptr_t)ji_227;
  if(n>228) vt[228]=(uintptr_t)ji_228;
  if(n>229) vt[229]=(uintptr_t)ji_229;
  if(n>230) vt[230]=(uintptr_t)ji_230;
  if(n>231) vt[231]=(uintptr_t)ji_231;
  if(n>232) vt[232]=(uintptr_t)ji_232;
  if(n>233) vt[233]=(uintptr_t)ji_233;
  if(n>234) vt[234]=(uintptr_t)ji_234;
  if(n>235) vt[235]=(uintptr_t)ji_235;
  if(n>236) vt[236]=(uintptr_t)ji_236;
  if(n>237) vt[237]=(uintptr_t)ji_237;
  if(n>238) vt[238]=(uintptr_t)ji_238;
  if(n>239) vt[239]=(uintptr_t)ji_239;
  if(n>240) vt[240]=(uintptr_t)ji_240;
  if(n>241) vt[241]=(uintptr_t)ji_241;
  if(n>242) vt[242]=(uintptr_t)ji_242;
  if(n>243) vt[243]=(uintptr_t)ji_243;
  if(n>244) vt[244]=(uintptr_t)ji_244;
  if(n>245) vt[245]=(uintptr_t)ji_245;
  if(n>246) vt[246]=(uintptr_t)ji_246;
  if(n>247) vt[247]=(uintptr_t)ji_247;
  if(n>248) vt[248]=(uintptr_t)ji_248;
  if(n>249) vt[249]=(uintptr_t)ji_249;
  if(n>250) vt[250]=(uintptr_t)ji_250;
  if(n>251) vt[251]=(uintptr_t)ji_251;
  if(n>252) vt[252]=(uintptr_t)ji_252;
  if(n>253) vt[253]=(uintptr_t)ji_253;
  if(n>254) vt[254]=(uintptr_t)ji_254;
  if(n>255) vt[255]=(uintptr_t)ji_255;
}
